### ISSUE TITLE
SELinux and Google 

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#100]
Google is removing apps from Play Store that changes SELinux policy. 
:-(

However, could you make a downloadable plug-in that adds SELinux feature back to Kernel Adiutor? That plug-in could be downloaded on your github or Google+ community.

I understand that users can use terminal and issue "setenforce 0", generate a init script to set it to permissive at boot up, use old Kernel Adiutor / SELinux editor app via apk, etc. but it'll be better to keep kernel editing in one place (and updated). Info regarding plug-in support won't be mentioned in the app and in the Play store changelog. If it's just not worth the risk of Kernel Adiutor being torn down from the Play Store even with the "hidden" plug-in, you can instead give users instructions in Adiutor's in-app FAQ (or in Misc. Control tab where policy editor was) on how to edit SELinux policy and set policy changes on boot.

Just a thought.

**Comment by Grarak** [comment]
I am not going to risk that KA gets banned from the store.
