### ISSUE TITLE
wlan_rx and msm_hsic wakelock dividers

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#101]
Rather than having just an on/off switch, an int divider is more useful to have less wakelock usage but keeping the wakelock enabled (you can maintain the old on/*off toggles also, the paths are different)

wlan_rx wakelock divider
/sys/module/bcmdhd/parameters/wl_divide (int from 1 to 8 for example)

msm_hsic wakelock divider
/sys/module/xhci_hcd/parameters/wl_divide (int form 1 to 8 for example)

edit: you can also do a percentage slider like on vibration intensity, because basicly goes from 1 that's is 100%, on 2 is 50%, on 4 25%, 8 i s 12,5% and so on until 0% which disables it

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/f6e6693d1b4c35f6643d68006c57cfa6f667382a

**Comment by engstk** [comment]
thanks mate
