### ISSUE TITLE
Flash/Backup kernel

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#103]
Flash or backup kernel through Kernel Adiutor. 

I know this app is meant to tweak the kernel settings rather than flashing kernels and all that crazy stuff, but I thought this would be pretty cool to have.

I've been trying to Google paths and how-tos on flashing kernels/recoveries in Android, but so far it isn't very clear. There are apps that do this though, but most of them seemed to be closed sourced. However I found this app that might help:  https://github.com/dslnexus/Rashr

If you want me to poke through his project and post some of the code/paths/etc. I will do it.

**Comment by DerRomtester** [comment]
This is pretty difficult because every device has different partitions for the boot.img. I dont think it is a good idea to add this. It is safer to flash from recovery. Users can mess up their device if this feature is used wrong.

**Comment by MardonHH** [comment]
some devices also have combined recovery and kernel into boot.img which only can flashing a kernel via fastboot

**Comment by kentallenduke** [comment]
@DerRomtester I understand how risky flashing kernels can be..I once hard-bricked my device by being dozy and flashing the wrong type of kernel for my device.
There could be a warning that pops up, similar to how Privacy Guard pops up when requesting Root access for an app on Cyanogen based ROMs. In addition, it could say after selecting kernel to flash "Are you sure you want to flash this kernel (filename)"? After tapping OK, it can maybe prompt " Are you REALLY Sure? You may permanently make your device inoperable!!!!". After OK, flashes kernel and reboots. For different partitions, I honestly had no idea that it was different between devices. But Rashr app did it somehow, at least it got a pretty high ranking on Google Play. Also, since recovery feature is now in the latest Aduitor, it would be nice to have a kernel flasher with it too.

As for the combined recovery and kernel @MardonHH my phone is honami, which almost all the time comes with recovery in the boot.img. You don't have to flash kernel through fastboot, I used Rashr to do that within Android and through TWRP and it works!

**Comment by MardonHH** [comment]
@kentallenduke  that wont work on some older sony devices. You can only flash kernel with fastboot on these devices

**Comment by kentallenduke** [comment]
@MardonHH Hmm...do you happen to have an old legacy phone lying around somewhere? Can you see if Rashr denies flashing kernel/recovery for the device? Unfortunately like you said it's only accessible via fastboot, which on some devices is disabled.. :-/
http://forum.xda-developers.com/showthread.php?t=2038759

**Comment by kentallenduke** [comment]
@MardonHH Correct me if I'm wrong, flashing kernel through app on the old Xperia line won't actually overwrite the current kernel? If so, then Adiutor can attempt to write but fail, can say at the end "Flashing kernel was Unsuccessful. Please check to see if your device supports flashing without fastboot". 

Sorry for not updating my comment, thought it'll be better to post a new reply.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/e833767c796aeccc9af2cb457da28da44284e347
