### ISSUE TITLE
Kernel Uber - L

### ISSUE THREAD

**Issue by Android-Mailson** [Grarak/KernelAdiutor#105]
you can add support for this kernel? Please
https://github.com/Cl3Kener/UBER-L

https://github.com/UBERTC/

**Comment by DerRomtester** [comment]
What do you mean ? This app should work on any kernel. You could ask the dev to add features that are missing in his app.

**Comment by Android-Mailson** [comment]
the sound does not work!

**Comment by DerRomtester** [comment]
What do you mean the sound ? You install the app and your sound is gone? Or do you need faux sound control or franco sound control or boeffla sound control ?

**Comment by Android-Mailson** [comment]
This kernel supports sound, plus the app does not change

**Comment by Grarak** [comment]
This kernel support faux sound. It's already added.
