### ISSUE TITLE
Can dashclock-api be used from mavenCentral?

### ISSUE THREAD

**Issue by krt16s** [Grarak/KernelAdiutor#107]
Was there a reason not to use `compile 'com.google.android.apps.dashclock:dashclock-api:2.0.0'` but rely on the jar file?

**Comment by Grarak** [comment]
The site is often down. So better use the jar.

**Comment by krt16s** [comment]
Haven't experienced any serious downtimes for jCenter or mavenCentral by now. However, since you pull other dependencies from there, the jar wont make you downtime-prove. I like to have dependecies in plaintext, especially since maven repositories can easily be switched to mavenLocal.

However, this is your project, so whatever suits your needs...

**Comment by Grarak** [comment]
By down I mean only the dashlclock api was unreachable. This already happened a few times.
