### ISSUE TITLE
Voltage Control via VDD sysfs

### ISSUE THREAD

**Issue by MardonHH** [Grarak/KernelAdiutor#109]
Still not supported...

**Comment by Grarak** [comment]
It got added with this commit
https://github.com/Grarak/KernelAdiutor/commit/7bcb3022ade10f66da865f79d433aad842c53bae

**Comment by MardonHH** [comment]
Nope thats only faux Voltage control what you added at "/sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels".

Real VDD Voltage Control support which i mean is at "/sys/devices/system/cpu/cpu0/vdd_levels"

**Comment by Grarak** [comment]
I didn't know that.
Then I need more informations to add it.

**Comment by MardonHH** [comment]
See: http://review.msm7x30.org/171

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/c318e15249a825c052365efb4fac3303a4155a90

**Comment by MardonHH** [comment]
new beta version later today?

**Comment by Grarak** [comment]
Probably not
if you want it immediately you can download it here
https://www.dropbox.com/s/ruq7rssc4jnmm60/app-release.apk?dl=0

**Comment by MardonHH** [comment]
Mhh... menu option is there, but it doesnt show actually used voltages...

![photo_2015-04-26_01-46-09](https://cloud.githubusercontent.com/assets/1421697/7335329/218f9ef0-ebb6-11e4-9fda-04458ff28b7d.jpg)

**Comment by Grarak** [comment]
Could you give me the content of this file?

**Comment by MardonHH** [comment]
122880:  900
  184320:  900
  245760:  900
  368640:  900
  460800:  950
  768000: 1050
  806400: 1100
  902400: 1125
 1017600: 1175
 1113600: 1200
 1209600: 1200
 1305600: 1225
 1401600: 1250
 1516800: 1275
 1612800: 1300
 1708800: 1350
 1804800: 1400

**Comment by Grarak** [comment]
This should fix it
https://www.dropbox.com/s/ruq7rssc4jnmm60/app-release.apk?dl=0

**Comment by MardonHH** [comment]
yes looks good
![photo_2015-04-26_02-24-36](https://cloud.githubusercontent.com/assets/1421697/7335404/7055f0c0-ebbb-11e4-8094-f126aab9b0eb.jpg)

**Comment by MardonHH** [comment]
hmm just realized voltage steps are 5mV steps.
VDD Voltage stepping should be in 25mV steps cause of regulator.
