### ISSUE TITLE
msm_hotplug controls

### ISSUE THREAD

**Issue by gummie09** [Grarak/KernelAdiutor#11]
Hi there,  is it possible to add msm_hotplug, the path is as below

/sys/module/msm_hotplug

Thanks Sir,

**Comment by gummie09** [comment]
/sys/module/msm_hotplug/boost_lock_duration
/sys/module/msm_hotplug/cpus_boosted
/sys/module/msm_hotplug/current_load
/sys/module/msm_hotplug/down_lock_duration
/sys/module/msm_hotplug/enabled
/sys/module/msm_hotplug/fast_lane_load
/sys/module/msm_hotplug/history_size
/sys/module/msm_hotplug/io_is_busy
/sys/module/msm_hotplug/load_levels
/sys/module/msm_hotplug/max_cpus_online
/sys/module/msm_hotplug/min_cpus_online
/sys/module/msm_hotplug/offline_load
/sys/module/msm_hotplug/uevent
/sys/module/msm_hotplug/update_rates

**Comment by Grarak** [comment]
Would be nice if you could get the min and max values of these settings
and a short description what they do

**Comment by RIPng** [comment]
ueventd is not a value of the hotplugging

**Comment by RIPng** [comment]
I looked further into the driver to assist, it appears there are the values and my take on what they are for

.msm_enabled = HOTPLUG_ENABLED, (Enables hotplug when value is 1, disables as 0)
	.min_cpus_online = DEFAULT_MIN_CPUS_ONLINE, (minimum cores allowed online at any time)
	.max_cpus_online = DEFAULT_MAX_CPUS_ONLINE,(maximum number of cores online at any time)
	.cpus_boosted = DEFAULT_NR_CPUS_BOOSTED, (Number of cores plugged when threshold is reach, this one may be inccorect)
	.down_lock_dur = DEFAULT_DOWN_LOCK_DUR,(I believe this is the amount of time it waits before unplugging a core)
	.boost_lock_dur = DEFAULT_BOOST_LOCK_DUR,(I believe this is the timer for a boost frequency activity such as touchboost or cpu boost driver would operate)
	.fast_lane_load = DEFAULT_FAST_LANE_LOAD(threshold for plugging another core)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/fb55eb2316b34dc95570cd0036117173dd492949
