### ISSUE TITLE
CPU Quiet a power saving driver for Nvidia tegra chipsets

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#110]
Nvidia chipsets uses powersavin driver called CPU quiet..and the respective paths to be edited as follows..

To enable CPU quiet : 
/sys/devices/system/cpu/cpuquiet/cpuquiet_driver/enabled

Available governors : 
/sys/devices/system/cpu/cpuquiet/available_governors
Contents : runnable load_stats

Current governor : 
/sys/devices/system/cpu/cpuquiet/current_governor

**Comment by Grarak** [comment]
I need a more detailed description.

**Comment by Cardinal97** [comment]
Cpuquiet implements pluggable policies for forcing cpu cores into quiescent state. Appropriate policies will save power without hurting performance.


I will post the Kconfig link also...would be helpful think so..

https://android.googlesource.com/kernel/tegra/+/android-tegra-flounder-3.10-lollipop-release/drivers/cpuquiet/Kconfig

**Comment by Grarak** [comment]
I'm not sure about the available governors.
How does the kernel prints out them?

**Comment by Cardinal97** [comment]
Kernel prints it same as how it prints the available cpu governor...

**Comment by Grarak** [comment]
Ok thanks

**Comment by Cardinal97** [comment]
Thanks for adding it...
