### ISSUE TITLE
PIN feature

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#112]
Have a PIN to restrict access / certain features to Kernel Adiutor.

I realize SuperSU has a PIN feature that prohibits Superuser access for an app without typing the right PIN. However, most custom ROMs don't have SuperSU built into the ROM, instead using Cyanogen's Privacy Guard to give apps root access (and by default it's disabled unless you enable through development settings). It lacks a PIN feature.

There's screen locking, but personally I share my phone a lot. So I keep my phone without a PIN.

Google play apps like Lockit is there, but that's an extra app...and most of them are freemium/pay only/trash and ads.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/8c5d1ce702c3c812c51c00531faaf8d92c123fb5
