### ISSUE TITLE
Caf cpu-boost - per core functionality

### ISSUE THREAD

**Issue by RenderBroken** [Grarak/KernelAdiutor#113]
There is the ability to set the input boost freq per core using the caf version of cpu-boost. It's all done in a single sysfs file.  I would love to see this implemented. Thanks!

**Comment by RenderBroken** [comment]
If you need more information, feel free to ask.  I would love to help this app move forward.

**Comment by Grarak** [comment]
I need the path and the values which can't be applied to them

**Comment by RenderBroken** [comment]
So its the same as normal CPU-Boost except what you set for it. The sysfs is:

/sys/module/cpu-boost/parameters/input_boost_freq

So instead of just having a single value, you have multiple values in the same sysfs file like:

"0:1190400 1:1190400 2:1190400 3:1190400"

If you need more information let me know. Also if you need any info for msm_limiter let me know as well. That is the last piece before I can choose this amazing app over Synapse. You are doing a great job!

**Comment by Grarak** [comment]
And how do I set a new value?

**Comment by RenderBroken** [comment]
Also note that you can disable cou boost per core as well be setting one to "0" like:

"0:1190400 1:1190400 2:0 3:0"

The above means that I only want cpu-boost to operate on the first two cores.

**Comment by RenderBroken** [comment]
I am not sure where this stands, if you need more info just let me know. I know you are being overwhelmed right now due to the increasing popularity of your app so let me know if I can help with anything.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/0040025c406cf04d1abc4164b74b46d13ff2e064

**Comment by RenderBroken** [comment]
My freaking hero!!

**Comment by Cardinal97** [comment]
U have to consider big.LITTLE even for this...even my little cores shows the same frequency as of the big ones....Sorry to bother...But I had to tell to make ur app perfect...

**Comment by RenderBroken** [comment]
Can you provide the SYSFS for:

/sys/module/cpu-boost/parameters/input_boost_freq

Meaning, if you use standard CPU-Boost, it doesn't matter because the same value is used for all 8 cores. Whereas if they use the CAF variant, you can set it per core like in my example above. Can you let us know what it shows for you exactly?

**Comment by Cardinal97** [comment]
I can set individual frequencies...The thing to be implemented is that if the chipset is a HMP then frequencies for the little core should have been procured from little ones seperately(if u see the app source and changes for big.LITTLE) u can understand what am sayin....still for ur satisfaction this is the sysfs entry....


0:0 1:0 2:0 3:0 4:0 5:0 6:0 7:0
