### ISSUE TITLE
Double tap to wake issue : Nexus 7 2013 WiFi (flo)

### ISSUE THREAD

**Issue by dexmc** [Grarak/KernelAdiutor#114]
Double tap to wake works only if Half screen is enabled. The kernel I use supports full screen only.

**Comment by Grarak** [comment]
I need more informations? Kernel? Paths? Values?

**Comment by dexmc** [comment]
Elementalx.
How do I find the path?

**Comment by DespairFactor** [comment]
It's the same case on his Nexus 6 implementation, it does work on the entire device, it just only enables it when you select halfscreen.

**Comment by Grarak** [comment]
Half screen is defined as 1 in the app. Some kernels use 0 = Disable 1 = Half screen 2 = Fullscreen and other kernels 0 = Disable 1 = Enable.
I can't do anything about his. It's a dilemma.

**Comment by DespairFactor** [comment]
For what its worth elementalx uses only 1 and 0 as the values, I'm not sure what the issue he is really reporting is, there is nothing to be fixed from my perspective
