### ISSUE TITLE
zen decision support

### ISSUE THREAD

**Issue by DespairFactor** [Grarak/KernelAdiutor#118]
- /sys/kernel/zen_decision/enabled (0 or 1): enable or disable the driver  Default: 1
- /sys/kernel/zen_decision/wake_wait_time (0-60000): How long to wait before executing CPU_UP work Default: 1000
- /sys/kernel/zen_decision/bat_thresold_ignore (0-100, 0=disabled): Don't do any CPU_UP work up to this battery charge level (e.g. if set at 15, and battery level is 15% or lower then don't attempt to bring CPUs online when screen comes on) Default: 15

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/5b374956d121b24ca930449aef60842918de4a79

**Comment by DespairFactor** [comment]
Thanks dude!
