### ISSUE TITLE
Pull down for refresh..

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#119]
Adding pull down to instantly refresh the app can be handy so that some values in the app can be refreshed without quittin nd coming in..I was actually thinkin about this only when i recognised that when night mode is toggled in cm12.1 the rgb value changes and night mode when switched off where still staying in the app keeps the value unchanged...So for the change to be visible the app was to be closed and reopend to make the value visible..So thats the need Jus like those in Google plus and FB app etc...

**Comment by Grarak** [comment]
This requires a full rewrite of all fragments. So no.
