### ISSUE TITLE
Mixed up francosound parameters

### ISSUE THREAD

**Issue by DJLaMontagneIII** [Grarak/KernelAdiutor#120]
Hi love the app. Noticed that francosound settings don't work correctly.

app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
    String MIC_BOOST = "/sys/devices/virtual/misc/soundcontrol/mic_boost";
    String SPEAKER_BOOST = "/sys/devices/virtual/misc/soundcontrol/mic_boost";
    String VOLUME_BOOST = "/sys/devices/virtual/misc/soundcontrol/mic_boost";

Should be:
app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
    String MIC_BOOST = "/sys/devices/virtual/misc/soundcontrol/mic_boost";
    String SPEAKER_BOOST = "/sys/devices/virtual/misc/soundcontrol/speaker_boost";
    String VOLUME_BOOST = "/sys/devices/virtual/misc/soundcontrol/volume_boost";

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/b5a425d63fb3c34ca7b792ab79d035e345da1116

**Comment by Grarak** [comment]
Copy and paste fail. Thanks.
