### ISSUE TITLE
Colour picker for action bars..

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#122]
Can u add colour picker for selecting individual colours of Action bar for each tabs upon user interest?? Multi colours make the app more cool..Or it is minimally enough if u just add Different ones for each tab without colour picker....

**Comment by Grarak** [comment]
That's unnecessary IMHO. Just fils up the data and the app needs more time to open each tab.

**Comment by Cardinal97** [comment]
Ya i accept that its unrelated to feature and just a UI improvement...that was jus a opinion...I didnt knew that  having seperate colours would take more data..Anyways it was jus a small opinion..And still its open source..So I have an option to make this myself...Thanks for this app being opensource..U have a generous mind seriously.. :)
