### ISSUE TITLE
Kernel log dump?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [Grarak/KernelAdiutor#123]
I was wondering why there's no option for this...last dmesg, last_kmsg and so on :)

Thank you in advice if you gonna implement it

**Comment by Grarak** [comment]
Hmmm already there?

**Comment by julianxhokaxhiu** [comment]
I didn't found the option. Can please point me where?

**Comment by julianxhokaxhiu** [comment]
Found it, nvm sorry :)
