### ISSUE TITLE
Touch Boost problem

### ISSUE THREAD

**Issue by Fabi9228** [Grarak/KernelAdiutor#124]
Hi, thanks for your work, again.

I have a nexus 5 and i love kernel RACER and HELLS CORE.
these kernels, use touchboost but kernel adiutor doesn't seem to manage well these frequencies.

Everything is messed up.
Some might check?

Sorry for the bad English

**Comment by Grarak** [comment]
How about providing more informations?
I don't have a nexus 5 running those kernels?!

**Comment by Fabi9228** [comment]
Yes, i will post a screenshot late ...
When i have kernel adiutor, the minimal frequency is 960 Mhz (not configure it) 
When i disable it (KA) the minimal frequency returns on 300Mhz (minimal exatly)

This problem happens with some kernels.
Others have no problems.

Bho, i don't know :/

**Comment by zwliew** [comment]
What do you mean by "have" and "disable"? Disable what (option) exactly in Kernel Adiutor?

**Comment by DespairFactor** [comment]
Touchboost is a listener that is called in the cpufreq governors. CPUboost was ripped out by some devs in favour of this input boost method. Others have update cpuboost to be less aggressive and more useful. What he is referring to as broken is probably nothing broken, it is likely due to the input from his touch on the display.

**Comment by Fabi9228** [comment]
by bad english :/
lately ... hellscore and racer have changed style.
Now, everything works fine.
When I had to manage all CPU boost, there were errors

Here's what I mean:
https://dl.pushbulletusercontent.com/cTxuMJyMEIilWSnXJkGPqDH92m4EQeqi/Screenshot_2015-06-07-10-44-04.png
https://dl.pushbulletusercontent.com/EHgufcN8QTFlU2ritWcuuKVPsehiWIAf/Screenshot_2015-06-07-10-44-31.png
