### ISSUE TITLE
AutoSMP and Dynamic management of dirty page writebacks

### ISSUE THREAD

**Issue by Micky007** [Grarak/KernelAdiutor#127]
Please can you add support to AutoSMP hotplug driver by mrg666 and to Dynamic management of dirty page writebacks by Christopher83 ?I wish you to have a good development

**Comment by Grarak** [comment]
Paths?????

**Comment by Grarak** [comment]
Reopen if you get some useful informations

**Comment by Micky007** [comment]
ok,I'll try to give you more informations in future
