### ISSUE TITLE
Reverse scrolling

### ISSUE THREAD

**Issue by R3gi** [Grarak/KernelAdiutor#128]
Middle mouse button is scrolling in reverse direction. When you scroll down, the page should move up so you could see the content in the lower part.
Tested on SE Xperia Mini (st15i, smultron), 320x480 MDPI.

**Comment by Grarak** [comment]
Bug reporting is getting ridiculous. This has nothing to do with the app. Get a new mouse or phone. Not my problem.

**Comment by R3gi** [comment]
I think it does, because in all other apps it's working as expected, only in Your app not. This reaction makes me sad, I am reporting this issue in order to help make the app better.

**Comment by Grarak** [comment]
Ok then answer one question.Why should I change the scroll direction of the mouse? Ask Google it's their SDK.

**Comment by R3gi** [comment]
On my Linux and Windows desktop when I scroll with a mouse wheel, rolling the mouse wheel "up" (rolling the top away from me) makes the page go "down" (in that I end up at the top of the page if I go far enough). In my opinion it's a natural behavior on almost all widely spread platforms.

As I said, Kernel Adiutor is the only app I've found it's scrolling in reverse direction. I don't know what's written in Android SDK, I am not a developer, but even Google's apps and system apps are scrolling "normally", as decribed above. If nothing else I would expect all my Android applications to behave in the same way.

(Notice I am still talking about the scroll direction of the mouse, scrolling by fingers works perfectly.)

**Comment by R3gi** [comment]
Hello, I am sorry, may I ask what's the conclusion? I know many Android users probably doesn't control their device with a mouse, but I do and this strange behaviour really affects my user experience. I've tested many various apps on various devices and Kernel Adiutor is really the ONLY app which behaves abnormally when comes to scrolling using the mouse wheel.
Would be please possible to reconsider it again? Or at least add some option/workaround for it…
Thank you,
R3gi

**Comment by Grarak** [comment]
I just tested it with KA and Google Play Store. Scrolling works the same with both apps. It's because of the Recyclerview. So no if you want this be fixed then ask Google.

**Comment by R3gi** [comment]
@Grarak Thank you for the reply. I made a short video which shows that the scrolling behavior is not the same: https://www.youtube.com/watch?v=DgZP86qiirk
As I said, I haven't found any app (except Kernel Adiutor), which would scroll in reverse direction – therefore I still can't understand why it isn't a bug (sure, from a user's perspective, as we know developer's point of view may be different :))…
Anyway, I have to accept it. Thank you again for Your time and I hope it will be fixed one day (no matter who will fix it).
R3gi
