### ISSUE TITLE
Nexus 6 tunables

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#13]
Hope you can merge some nice tunables for N6, some work also for N5

# Tap2Wake
/sys/devices/f9966000.i2c/i2c-1/1-004a/tsp (string "AUTO" or "OFF)

# Vibration intensity N6
/sys/vibrator/pwmvalue (integer from 0~127)

# blu_plug CPU Hotplug
/sys/module/blu_plug/parameters/down_timer_cnt (integer 1~10)
/sys/module/blu_plug/parameters/up_timer_cnt (integer 1~10)
/sys/module/blu_plug/parameters/min_online (integer 1~4 min cores online)
/sys/module/blu_plug/parameters/max_online (integer 1~4 max cores online)
/sys/module/blu_plug/parameters/max_cores_screenoff  (integer 1~4 max cores online while in screenoff)
/sys/module/blu_plug/parameters/max_freq_screenoff (integer frequency max while in screenoff)
/sys/module/blu_plug/parameters/up_threshold (integer 0~100 load Up Threshold)

# Simple GPU Governor extension to msm_adreno_tz in N6
/sys/module/simple_gpu_algorithm/parameters/simple_gpu_activate (true/false as 1/0)
/sys/module/simple_gpu_algorithm/parameters/simple_laziness (integer, same values as N5)
/sys/module/simple_gpu_algorithm/parameters/simple_ramp_threshold (integer, same values as N5)

# Delay Writebacks (laptop mode)
/proc/sys/vm/laptop_mode (true/false as 1/0)

**Comment by Grarak** [comment]
All controls have been added!

**Comment by engstk** [comment]
Thanks mate!
