### ISSUE TITLE
Custom Battery Charge Control..

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#130]
Can u fetch my repo and cherry pick this commit...

54dd65b2a36b99242cd54de64d326c82151b51e7

This is actually acustom battery charging rate control for yureka devices...Thanks in advance..

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/a07357e753a3cd2a3a31b9a71b8c1b5b2232f61c
