### ISSUE TITLE
[REQUEST} Anti-Smearing Fix on AMOLED displays 

### ISSUE THREAD

**Issue by asad007** [Grarak/KernelAdiutor#132]
These are the sys paths

/sys/class/misc/mdnie/black_increase_point
/sys/class/misc/mdnie/black_increase_value
/sys/class/misc/mdnie/brightness_input_delta
/sys/class/misc/mdnie/brightness_reduction
/sys/class/misc/mdnie/brightness_takeover_point

**Comment by Grarak** [comment]
min max values, how to apply new values, etc. Same goes for your wolfson issue. Closed until you got those things. And a detailed description what everything does.

**Comment by asad007** [comment]
this might be helpful :
https://mega.co.nz/#!sEdX0A7Q!ZREKCG_sDoTRY1tyjx4o-iXbCqjsbP4XW9N6NZc9oXk

black increase value : min=0 max=5
Brightness reduction : min=0 max=128
Takeover point : min=0 max=64
Brightness input delta : min=0 max=64

Hope it is a start ( I'll research more if needed )
