### ISSUE TITLE
Please make the Kernel informations more like a table

### ISSUE THREAD

**Issue by mattis102** [Grarak/KernelAdiutor#134]
Please set the same space between the information title like MemTotal: and the value.
Like:
MemTotal:      000
MemFree:       000

**Comment by Grarak** [comment]
This is how the kernel prints it out. I won't change that.

**Comment by mattis102** [comment]
Ok not on my Phone. Maybe bcs of the force rtl-layout? Could this be possilbe?

**Comment by Grarak** [comment]
What? No? I tell you again the KERNEL prints out the memory informations like that.

**Comment by mattis102** [comment]
Ok sry my english is to bad but now i got it
