### ISSUE TITLE
Can't Weaken Sound Modifiers

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#135]
Hi, 
I'm really liking the sound feature Kernel Adiutor has built-in to the app! I use it whenever I play a movie to get more of a bass. 
The only issue I have with the sound tweaking is that I can move the slider to the right to get more amps + bass boost, but I can't slide it to the left to weaken it. When I slide it to the left it doesn't get weaker. The only way to make it weak again is to reboot. 
By default, it says that Sound/Poweramp gain's value is not supported, But I can slide to the right to make adjustments, however not to the left.
Is this a problem with the kernel I have? I'm on Android 5.1.1 Xperia Z1 (honami) using Resurrection Remix's GreatDev kernel (slim kernel), but it also happens on all Cyanogenmod Lollipop based kernels for my device.

**Comment by Grarak** [comment]
Every device has different max min values. I won't fix that.
