### ISSUE TITLE
Add Additional Widgets

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#136]
I would really like more widgets for Kernel Adiutor, besides the Profile that we have at the moment.

There could be informative widgets, like CPU level, CPU temperature, RAM usage, frequency table, etc. 
There also could be widgets that has some functionality like the Profile widget we have, adjusting CPU/GPU frequency, HotPlug, Sound, etc.

All those widgets can be grouped into one. Selecting the widget and dragging down to desktop from Google Now launcher will bring part of Kernel Adiutor's interface with a selection of what widget to put on to the desktop.

**Comment by Grarak** [comment]
Sorry. Won't happen. Widgets are very limited in Android.
