### ISSUE TITLE
autosmp hotplug by mrg666

### ISSUE THREAD

**Issue by DerRomtester** [Grarak/KernelAdiutor#137]
Enable/Disable
/sys/module/autosmp/parameters/enabled 
Y ( for enabled)
N (for disabled)

Percentage values for downrate limits
/sys/kernel/autosmp/conf/cpufreq_down
(range from 0 - 100)

Percentage values for uprate limits
/sys/kernel/autosmp/conf/cpufreq_up
(range from 0 - 100)

Cycles to wait after the last hotplug event to unplug another core
/sys/kernel/autosmp/conf/cycle_down
(values 0 1 2 3 4)

Cycles to wait after the last hotplug event to plug another core
/sys/kernel/autosmp/conf/cycle_up
(values 0 1 2 3 4)

Delay
/sys/kernel/autosmp/conf/delay
(range from 0 - 500)

Maximum CPUs online at any time
/sys/kernel/autosmp/conf/max_cpus

Minimum CPUs online at any time
/sys/kernel/autosmp/conf/min_cpus

Use only one core when screen is offline
/sys/kernel/autosmp/conf/scroff_single_core
1 (=enabled)
0 (=disabled)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/938955d180b5f54296ee013e17461dd16767cced
