### ISSUE TITLE
Temperature threshold (francos thermal driver)

### ISSUE THREAD

**Issue by DerRomtester** [Grarak/KernelAdiutor#138]
This allows to throttle cpu frequencys when temperature reaches a certain degree
/sys/module/msm_thermal/parameters
°C suggested values from 40 - 100

**Comment by Grarak** [comment]
This is a directory not a file.

**Comment by DerRomtester** [comment]
Ups sry forgot that 
/sys/module/msm_thermal/parameters/temp_threshold

**Comment by Grarak** [comment]
Already added.

**Comment by DerRomtester** [comment]
Thx man you are fast

**Comment by Grarak** [comment]
It was added 3 months ago
https://github.com/Grarak/KernelAdiutor/commit/fe6ac2289683f72a8b34b18302263797d3b98e7f

**Comment by DerRomtester** [comment]
I only was wondering why it does not show up for me
