### ISSUE TITLE
enable/disable smb135x wakelock on N6

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#14]
Can you add this N6 tunable mate?
It's related to power (maybe put on misc tab?)

"enable/disable smb135x wakelock"
/sys/module/smb135x_charger/parameters/use_wlock (Y or N)

**Comment by engstk** [comment]
This kills wakelock on N6 when Ambient Display is disabled

**Comment by Grarak** [comment]
Does this kills wakelocks when it's enabled or disabled?

**Comment by engstk** [comment]
True -> wake lock is enabled

**Comment by Grarak** [comment]
Added
https://github.com/Grarak/KernelAdiutor/commit/441858e61155af3300da6f712c6816f959e82bdd

**Comment by engstk** [comment]
Thanks mate!
