### ISSUE TITLE
CPU UV - Save values for boot instead of offset

### ISSUE THREAD

**Issue by metinkale38** [Grarak/KernelAdiutor#140]
When using CPU Undervolt (at least with global offsets)  automatic on Boot, just the offset is saved and not the values. If I make a soft reboot, the offset is set again, and the phone crashs/restarts (because the cpu has too low V). 

If you would set the correct values on boot instead, this wouldn't happen...

**Comment by Grarak** [comment]
Then make a full reboot?

**Comment by metinkale38** [comment]
It is just a suggestion, it isn't a problem for me...

**Comment by Grarak** [comment]
It's not possible to detect that a user does a soft reboot. So it's not possible.
