### ISSUE TITLE
Timer slack controller and dynamic management of the minimal timer slack value 

### ISSUE THREAD

**Issue by Micky007** [Grarak/KernelAdiutor#143]

**Comment by Micky007** [comment]
I

**Comment by Micky007** [comment]
The timer slack controller is a feature developed by Kirill Shutemov and it allows to set the minimal timer slack value for every process contained within a control group (cgroup).
A timer slack allows the kernel to manage processes wakeup requests at some future time.
Thanks to this feature, the kernel can set a specific timer slack for the involved processes, minimizing the number of wakeups and allowing a lower system's power consumption.

Three new cgroup parameters are exposed inside each processes hierarchy contained in /dev/cpuctl path:
- timer_slack.min_slack_ns is the timer slack used when the system is active for the current processes hierarchy
- timer_slack.min_slack_suspend_ns is the timer slack used when the system is suspended for the current processes hierarchy
- timer_slack.effective_slack_suspend_ns is the timer slack currently used

1) By directly editing one of the file written above inside /dev/cpuctl and inside each hierarchy subfolder, by setting the preferred value (note that set value will be lost after a reboot/shutdown)

**Comment by Micky007** [comment]
Excuse me for the mess I've did closing and reopening twice but I've tapped many times where I shouldn't, at anyway please add this feature to your app and I wish you to have a good development

**Comment by Grarak** [comment]
min max values
