### ISSUE TITLE
Provide build without play-services

### ISSUE THREAD

**Issue by krt16s** [Grarak/KernelAdiutor#146]
Google's play-services is a non-free dependency which cannot be build by fdroid. Could you consider adding a gradle build flavour that works without it?

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/638c5b889ab56e1f05bf793ea524582087c71db9

**Comment by krt16s** [comment]
Thanks for the quick response. You might want to look into [ACRA](http://www.acra.ch/) or [gradle build flavors](https://developer.android.com/tools/building/configuring-gradle.html) if crash reports and analytics are needed.
