### ISSUE TITLE
Reset Tweaks

### ISSUE THREAD

**Issue by tarek133** [Grarak/KernelAdiutor#147]
Hey there,
at first: Great Work!
But can you please add a function, which reset all setting are made?
By the way, I have problems with the "Low Memory Killer". 
What's that, and which setting is best? 
"Aggressiv", "Sehr Aggressiv", "Mittel", "Sanft", Sehr L
leicht". Pleasr help me :)

**Comment by Grarak** [comment]
Already requested and nope it's not possible. Reboot your device if you want default settings back.

**Comment by tarek133** [comment]
Thank's anyway!
