### ISSUE TITLE
A wear Version possible?

### ISSUE THREAD

**Issue by ReinhardStrauch** [Grarak/KernelAdiutor#148]
Your kernelaudiutor runs fine in Android wear in my LG g watch!

Is it possible to make a layout for small screens/Android wear?

Regards and thanks

Reinhard Strauch

re.strauch@gmail.com

**Comment by Grarak** [comment]
I would need a real Android Watch to do this.

**Comment by ReinhardStrauch** [comment]
Emulator doesn't do it?

THX!

**Comment by Grarak** [comment]
no
