### ISSUE TITLE
enable/disable faux sound control on N6

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#15]
Mate can you add this tunable to faux sound?

"enable/disable faux sound control"
/sys/module/snd_soc_wcd9320/parameters/enable_fs (Y or N)

**Comment by Grarak** [comment]
Do you have a short description what this tunable does?

**Comment by engstk** [comment]
It really is a enable/disable Faux sound driver.
Maybe it should go in the sound tab next to the other faux sound tunnels

**Comment by Grarak** [comment]
Added
https://github.com/Grarak/KernelAdiutor/commit/441858e61155af3300da6f712c6816f959e82bdd

**Comment by engstk** [comment]
Thanks mate!

**Comment by Shoaib0597** [comment]
The toggle doesn't shows up on my kernel with FauxSound v3.4. What changes do I have to make in order to get that switch? @engstk

**Comment by AayushJainRd7** [comment]
@Shoaib0597 It is Very Much Working :package: Kindly check that Properly
For 3.4(or in May be 3.6 not quite sure of) onwards u have to enable 2 things on ur Defconfig and nt one

**Comment by Shoaib0597** [comment]
@AayushRd7,  What's the second option?

**Comment by AayushRd7** [comment]
Sorry Bro my bad...I was using a modified Kernel adiutor :l That'ss Why I was getting 
Nd on v3.4 onwards 


These are the things to be enabled:


CONFIG_AUDIO_EXT_CLK=y
 +CONFIG_SND_SOC_WCD_MBHC=y
