### ISSUE TITLE
Tasker Integration

### ISSUE THREAD

**Issue by bcozimme** [Grarak/KernelAdiutor#152]
Please make Tasker work with Kernel Auditor!
Everyone will love it <3

**Comment by Grarak** [comment]
Already request the answer is no

**Comment by Grarak** [comment]
I did think about this feature. And came up with an easy implementation. I will reopen this for now.
I thought about following. Apply your selected profiles when:

Charging
Wifi on/off
Open/Close Apps
Screen on/off

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/9ca65cf880b578c59896f17999a89f6cd59eade3
