### ISSUE TITLE
Apply on boot toggle bug

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#153]
When i scroll down through a fragment apply on boot gets disappeared....when i do a long scroll there is no problem apply on boot appears again when I reach the fragment starting...But if a do a short scroll meaning jus scrolling through two or three options in that fragment apply on boot isnt appearing after going to the fragment's intial point...If the feature list of the fragment is lengthy its ok...i can manage by doing a long scroll and bring back apply on boot...But when the feature list is too short but scrollable and if I scroll am not getting the apply on boot...

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/492490f880f74442cae842b180ffa3804198829e
