### ISSUE TITLE
Add option to enable/disable perfd

### ISSUE THREAD

**Issue by Kra1o5** [Grarak/KernelAdiutor#154]
Hi in future versions you can add option to enable/disable perfd? same as you do with MPDecision.

Because new devices now use perfd instead of MPDecision.

Greetings

**Comment by Grarak** [comment]
I need descriptions. How to turn it on/off?

**Comment by Kra1o5** [comment]
I cant find much about perfd & not see the way to enable/disable manually.

**Comment by deadman96385** [comment]
There is not a sysfs to enable or disable it

**Comment by Kra1o5** [comment]
Yeah is what I see.
