### ISSUE TITLE
Exynos 5420 MIF and INT Voltage Control

### ISSUE THREAD

**Issue by deadman96385** [Grarak/KernelAdiutor#156]
/sys/devices/platform/exynos5-busfreq-mif/devfreq/exynos5-busfreq-mif/governor
/sys/devices/platform/exynos5-busfreq-mif/devfreq/exynos5-busfreq-mif/freq_table
/sys/devices/platform/exynos5-busfreq-mif/devfreq/exynos5-busfreq-mif/volt_table
/sys/devices/platform/exynos5-busfreq-mif/devfreq/exynos5-busfreq-mif/max_freq
/sys/devices/platform/exynos5-busfreq-mif/devfreq/exynos5-busfreq-mif/min_freq

/sys/devices/platform/exynos5-busfreq-int/devfreq/exynos5-busfreq-int/governor
/sys/devices/platform/exynos5-busfreq-int/devfreq/exynos5-busfreq-int/freq_table
/sys/devices/platform/exynos5-busfreq-int/devfreq/exynos5-busfreq-int/volt_table
/sys/devices/platform/exynos5-busfreq-int/devfreq/exynos5-busfreq-int/max_freq
/sys/devices/platform/exynos5-busfreq-int/devfreq/exynos5-busfreq-int/min_freq

#Auxiliary voltage controls for the internal, memory interface and memory IO voltage plane

**INT** (Internal) voltage is the voltage supplied to the internal auxiliary IP blocks, such as the hardware video decoders, the scaling blocks, the image signal processors, the display controllers, and the MMC controllers.

**MIF** (Memory interface) voltage is the voltage supplied to the memory controller.
MEMIO (Memory I/O) voltage is the voltage supplied to the memory chip's IO interface. Also known as VDDQ. Voltage is tied to the memory controller's speed.

**Comment by Grarak** [comment]
This is an unstable feature from andreilux. Won't get added
