### ISSUE TITLE
Enable/Disable Logger Mode

### ISSUE THREAD

**Issue by deadman96385** [Grarak/KernelAdiutor#157]
A lot of kernels have disabled the logger by default to save ram an option in Kernel Adiutor would be sweet it would only need an on/off switch
/sys/kernel/logger_mode/logger_mode
0 Disabled (Default)
1 Enabled

**Comment by Grarak** [comment]
I need a more detailed description. What does this logger disable?

**Comment by deadman96385** [comment]
It enables/disables the entire logging system for the android kernel, lots of kernels across devices have it because if someone needs to generate a log they can enable it and then later disable it to save ram

**What the code looks like:**
https://github.com/LiquidSmooth-Devices/android_kernel_samsung_klimtwifi/commit/8c9a89372c584885ccc5bd6591184a995067ec63

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/4ea223e51c4d2e8f797308fec4e220a064ad884d
