### ISSUE TITLE
Some device gestures

### ISSUE THREAD

**Issue by DerRomtester** [Grarak/KernelAdiutor#158]
On my oneplus one i have following gestures available

Allows to open the camera by drawing a circle on the screen
/proc/touchpanel/camera_enable

Allows to open flashlight by drawing a V on the screen
/proc/touchpanel/flashlight_enable

This does enable the glove mode
/proc/touchpanel/glove_mode_enable

Allows to control music playback by drawing gestures on the screen
two fingers vertically to play/pause 
draw a left arrow to previous track a right arrow for the next track
/proc/touchpanel/music_enable

This enables smart2cover
/proc/touchpanel/smartcover_mode_enable

This enables sweep2wake
/proc/touchpanel/sweep_wake_enable

**Comment by Grarak** [comment]
Missing values.

**Comment by DerRomtester** [comment]
On my oneplus one i have following gestures available

Allows to open the camera by drawing a circle on the screen
/proc/touchpanel/camera_enable
0 = disabled 
1 = enabled 

Allows to open flashlight by drawing a V on the screen
/proc/touchpanel/flashlight_enable

0 = disabled 
1 = enabled 

This does enable the glove mode
/proc/touchpanel/glove_mode_enable

0 = disabled 
1 = enabled 

Allows to control music playback by drawing gestures on the screen
two fingers vertically to play/pause
draw a left arrow to previous track a right arrow for the next track
/proc/touchpanel/music_enable

0 = disabled 
1 = enabled 

This enables smart2cover
/proc/touchpanel/smartcover_mode_enable

0 = disabled 
1 = enabled 

This enables sweep2wake
/proc/touchpanel/sweep_wake_enable

0 = disabled 
1 = enabled
