### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by Fabi9228** [Grarak/KernelAdiutor#16]
awesome kernel manager 

I think that is missing:

gamma profiles (pierligio etc.) 
Es: https://s3.amazonaws.com/pushbullet-uploads/ujxJP9RS58K-CevSj3ShfglPbdGNvvQQQitwGsvZoMmZ/Screenshot_2015-02-07-18-58-31.png
https://s3.amazonaws.com/pushbullet-uploads/ujxJP9RS58K-X1IKT9BCiDyYlXNi3WoaTRq2YtWCRwMO/Screenshot_2015-02-07-18-58-17.png

soundcontrols profiles faux (quality, loudness and others)

wake timeout, power suspend key, wake gestures etc.

thanks

**Comment by FloGatt** [comment]
+1

**Comment by fawkes15** [comment]
+1

**Comment by Hybridmax** [comment]
Please add support for dynamic fsync by faux123 man :)

**Comment by Fabi9228** [comment]
if you can help
profiles them are here: http://forum.xda-developers.com/showthread.php?t=2424467

thanks!

**Comment by Punchieo** [comment]
+1

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/e46848b78fd6cf03938548616b2d14e925f54fbd
