### ISSUE TITLE
Refresh/Reload button for some fragments

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#160]
Can u add an refresh button on fragments with dynamic values like those screen fragments,cpu fragments etc....??

And there is also another idea for this refresh thing....Lik if I press the same fragment again from the navigation pane the fragment gets refreshed....for eg: am in CPU fragment and when i select the same from the navigation pane it gets refreshed/reloaded....

**Comment by Grarak** [comment]
You already requested this. Answer is still no. Recyclerview is a bitch that's why.

**Comment by Cardinal97** [comment]
Oh...i actually thought pulling down to refresh needs more coding.....Ok i got u now...refresh itself is an hectic thing... :P I wont ask it anymore..
