### ISSUE TITLE
Adreno Idler Driver

### ISSUE THREAD

**Issue by DespairFactor** [Grarak/KernelAdiutor#161]
Al information regarding the driver is here. Please let me know if you require anything else.

http://forum.xda-developers.com/android/software-hacking/adreno-idler-idling-algorithm-devfreq-t3134872#post61344789

**Comment by engstk** [comment]
/sys/module/adreno_idler/parameters
/sys/module/adreno_idler/parameters

**Comment by thao343** [comment]
G

**Comment by Grarak** [comment]
7ba68dedc48c92bda3901f1308dd3a048070abae
