### ISSUE TITLE
Sweep2Sleep doesn't work

### ISSUE THREAD

**Issue by discipuloosho** [Grarak/KernelAdiutor#162]
Hello. Sweep2Sleep doesn't write 0/1 (deactivate/activate) into /sys/android_touch/sweep2sleep file. Thanks.

**Comment by thao343** [comment]
Hi

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/2ee86f3827270730dbee0851834ea91c47a970fa
