### ISSUE TITLE
Program title spelled wrong in fdroid

### ISSUE THREAD

**Issue by snelltheta** [Grarak/KernelAdiutor#164]
Don't you mean auditor instead of audiutor?
Please forgive me if I'm missing something.

**Comment by DerRomtester** [comment]
It is called adiutor and not audiutor. I think this is inteded because it is a latin word and means sth like helper. https://en.wiktionary.org/wiki/adiutor

**Comment by DespairFactor** [comment]
For real? People keep opening this? Isn't there an answer for this in the app?:S
