### ISSUE TITLE
Touch Boost

### ISSUE THREAD

**Issue by blinnqipa** [Grarak/KernelAdiutor#165]
Can Touch Boost setting be added as a feature supported by many Kernels.

**Comment by RenderBroken** [comment]
I love this app so I will help where I can. I am not affiliated with this app what so ever though. 

You would really help speed this along if you could give more info about Touch Boost and the sysfs path for its tunable.

**Comment by blinnqipa** [comment]
@RenderBroken  thank you so mucb for your interest but I found the setting to change it ,it was burried deep in CPU governor tunables.

**Comment by RenderBroken** [comment]
Still, it would be helpful to add support in This app for it. If you can, just share the path to the sysfs file you found. Thanks!

PS: Glad you took the time to find it. Some would have not even tried.
