### ISSUE TITLE
Double tap to wake on the Nexus 9

### ISSUE THREAD

**Issue by Beta1440** [Grarak/KernelAdiutor#166]
Full screen double-tap to wake does not work on the N9. However all the other gestures like halfscreen double-tap to wake, sweep to wake, and sweep to sleep work fine.

To enable full screen dt2w, I believe the command is: 
echo 1 > /sys/devices/platform/spi-tegra114.2/spi_master/spi2/spi2.0/input/input0/wake_gesture

Here is the commit to add support for the N9 (I'm not sure if it's relevant): 
https://github.com/flar2/ElementalX-N9/commit/fd1e094d96941b126decacca050474ed0df4f44f

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/1fabd4b04c72c428ed0ff515d633367c40aa25d7
