### ISSUE TITLE
[Enhancement] Add virtual memory tunable for extra_free_kbytes

### ISSUE THREAD

**Issue by zwliew** [Grarak/KernelAdiutor#167]
extra_free_kbytes tunable

Description:
Changes the amount of memory that the kernel tries to keep free, affecting allocation time and the frequency of lowmemorykiller running.

SYSFS directory:
/proc/sys/vm/extra_free_kbytes

Usage:
echo (any integer) > /proc/sys/vm/extra_free_kbytes

Thanks in advance! :)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/7a826510da87f4247c66f1f630530e8de84faf84
