### ISSUE TITLE
Additional wakelock sources

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#168]
Can you update wakelock toggles to this paths?

smb135x Wakelock (Prevent charger wakelock)
/sys/module/wakeup/parameters/enable_smb135x_wake_ws (Y/N)

wlan_ctrl Wakelock (Prevent wlan_ctrl wakelock)
/sys/module/wakeup/parameters/enable_wlan_ctrl_wake_ws (Y/N)

wlan_rx Wakelock (Prevent wlan_rx wakelock)
/sys/module/wakeup/parameters/enable_wlan_rx_wake_ws (Y/N)

wlan_wake Wakelock (Prevent wlan_wake wakelock)
/sys/module/wakeup/parameters/enable_wlan_wake_ws (Y/N)

**Comment by Grarak** [comment]
0ca8f0907fc50da82b597d46958fdb46a33521f1
