### ISSUE TITLE
Kernel permissions 

### ISSUE THREAD

**Issue by zimlokks** [Grarak/KernelAdiutor#17]
It would be a good idea to set necessary permissions to all the tunable files, my device LG F6 for example can't change the governor because the permissions are set to 444 and not what they're supposed to be in which I set them to 777.

**Comment by Grarak** [comment]
I can't do that for all file. This would cause lags. Instead I changed the scaling governor file to 644 permission.
https://github.com/Grarak/KernelAdiutor/commit/77ec45997a6b7f01a223c96bed44ba4b995380bb
