### ISSUE TITLE
app_name removed from translation strings?

### ISSUE THREAD

**Issue by pejakm** [Grarak/KernelAdiutor#174]
Hi, may I ask why this change? In Serbian we find that also aplication/program name must be written in Cyrillic script, otherwise it is not translated. If the program's name is a brand, then we just transliterate it, otherwise we translate/adapt. In this case, Kernel Adiutor was simply written in Cyrillic script: *Кернел Адиутор*.

P. S. I realize Serbian translation is not yet completed, but it will be hopefully soon, as soon as I get more spare time. :)

**Comment by Grarak** [comment]
The app name shouldn't be translated IMHO.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/ba76d8393ad05c8a19495525cd8c8a78268eb6db
