### ISSUE TITLE
CPU Voltage Enhancement 

### ISSUE THREAD

**Issue by RenderBroken** [Grarak/KernelAdiutor#178]
I would love for when you lower or raise the voltage via Global Offset, that it remembered the amount you had originally set when you re-open it. So if you had set it to -50mv, played around and tested that setup for awhile and realize you could go lower, re-open Kernel Adiutor and open CPU Voltage again. When you tap Global Offset again, it would show -50 instead of 0.

**Comment by Grarak** [comment]
If you use any other app to modify the voltages afterwards. KA will not notice that and will show the wrong informations. So better leave it.

**Comment by RenderBroken** [comment]
What I am talking about does not have anything to do with any other Apps. If I were to use the "Global Offset" to set it to -70mv for example, when I hit OK, then open "Global Offset" again, it will show "0" instead of "-70".

This is helpful for those who push limits and test after each voltage change. They may not remember how far from Stock Voltage they are and would make it more difficult to track. 

Once again, this is only a suggestion for an already, amazing app. Keep up the great work!

**Comment by Grarak** [comment]
I know what you mean. Again read my previous answer

**Comment by RenderBroken** [comment]
Ok, thanks for your time.
