### ISSUE TITLE
C State control

### ISSUE THREAD

**Issue by DespairFactor** [Grarak/KernelAdiutor#18]
I believe the c states control would be a good option, sorry I don't currently know the sysfs portion for these, they are found in the faux kernel manager application.

**Comment by Grarak** [comment]
Without paths I can't do anything

**Comment by RIPng** [comment]
/sys/devices/system/cpu/cpu0/cpuidle/state0
/sys/devices/system/cpu/cpu0/cpuidle/state1
/sys/devices/system/cpu/cpu0/cpuidle/state2
/sys/devices/system/cpu/cpu0/cpuidle/state3

/sys/devices/system/cpu/cpu1/cpuidle/state0
/sys/devices/system/cpu/cpu1/cpuidle/state1
/sys/devices/system/cpu/cpu1/cpuidle/state2
/sys/devices/system/cpu/cpu1/cpuidle/state3

/sys/devices/system/cpu/cpu2/cpuidle/state0
/sys/devices/system/cpu/cpu2/cpuidle/state1
/sys/devices/system/cpu/cpu2/cpuidle/state2
/sys/devices/system/cpu/cpu2/cpuidle/state3

/sys/devices/system/cpu/cpu3/cpuidle/state0
/sys/devices/system/cpu/cpu3/cpuidle/state1
/sys/devices/system/cpu/cpu3/cpuidle/state2
/sys/devices/system/cpu/cpu3/cpuidle/state3

**Comment by Grarak** [comment]
I need a description what they do and how to read and apply settings.

**Comment by RIPng** [comment]
It is low power modes when the cpu is idle.

C0 is operating state(cpu is full power, referred to as wfi)
C1 is halt state(stops main internal CPU clock, faux refers to this as retention state)
C2 is stop clock(stops clocks from hardware, referred to as standalone pc by faux)
C3 is deep sleep(refered to as pc by faux

I have reached out to faux to get the c state sysfs toggles and default values, as it isn't as simple as I thought.

**Comment by Grarak** [comment]
Will close this for now
until I get more informations
