### ISSUE TITLE
Disable Section Titles and Add option to disable Whole section

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#185]
When all all sections under a particular head for eg. under "Tools" head... is disabled, it will be nyc if the head "Tools" is not showing up empty in the dashboard....

Also add an option to disable a total head in one single toggle...for convenience purpose...

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/bca7423098a0d41d642807de33b267c5928e3320

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/9015066a9304044a4931fb435435a84893450d61
