### ISSUE TITLE
Show Krait Variant

### ISSUE THREAD

**Issue by javelinanddart** [Grarak/KernelAdiutor#191]
/sys/kernel/debug/krait_variant
It will vary slightly depending on the device
Newer devices will have 7 PVS IDs, Older ones will have 4
A GUI showing the command line output would be useful

**Comment by javelinanddart** [comment]
Your krait chip variant is: 
[ ] SNAIL 
[ ] SLOWER 
[X] SLOW 
[ ] NOMINAL 
[ ] FAST 
[ ] FASTER 
[ ] OVER 3000! 
is the output for me
On older devices it will be
Your krait chip variant is: 
[ ] SLOW 
[X] NOMINAL 
[ ] FAST 
[ ] FASTER

**Comment by Grarak** [comment]
What do you mean with newer and older devices?

**Comment by javelinanddart** [comment]
First gen krait only has 4 variants, after that, there's 7.

**Comment by javelinanddart** [comment]
Not that important
