### ISSUE TITLE
fsync module

### ISSUE THREAD

**Issue by mostafa-z** [Grarak/KernelAdiutor#195]
fsync can enable or disable at this sysfs address
echo "Y" > /sys/module/sync/parameters/fsync_enabled;

tnx

**Comment by javelinanddart** [comment]
Does /sys/devices/virtual/misc/fsynccontrol/fsync_enabled not work?

**Comment by mostafa-z** [comment]
hmm im on msm8974ac (G3) stock kernel, i dont have your sysfs !!!

**Comment by javelinanddart** [comment]
Odd

**Comment by ShinySide** [comment]
echo "Y" > /sys/module/sync/parameters/fsync_enabled;

Same for the s5
