### ISSUE TITLE
Configuration for @SultanXDA's MSM_THERMAL Driver

### ISSUE THREAD

**Issue by javelinanddart** [Grarak/KernelAdiutor#198]

**Comment by javelinanddart** [comment]
The MSM8960/MSM8974 One
/sys/kernel/msm_thermal/enabled On/Off Switch (1 is enabled, 0 is disabled)
/sys/kernel/msm_thermal/low_thresh Low Thermal Throttling Settings (throttle_freq, throttle_temp, unthrottle_temp) (freq_low_thresh, trip_low_thresh, reset_low_thresh)
/sys/kernel/msm_thermal/mid_thresh Mid Thermal Throttling Settings (throttle_freq, throttle_temp, unthrottle_temp) (freq_mid_thresh, trip_mid_thresh, reset_mid_thresh)
/sys/kernel/msm_thermal/high_thresh High Thermal Throttling Settings (throttle_freq, throttle_temp, unthrottle_temp) (freq_high_thresh, trip_high_thresh, reset_high_thresh)

**Comment by javelinanddart** [comment]
Example of the MSM8960/MSM8974 One
https://github.com/sultanxda/android_device_oppo_msm8974-common/commit/cec3c47c6c60c8f2362df84b8b24d1c0ca262193

**Comment by RenderBroken** [comment]
I second this and am currently using this on 2 different kernels.

**Comment by ZdrowyGosciu** [comment]
:+1:

**Comment by javelinanddart** [comment]
Added Max Freq Override

**Comment by LuffyXDA** [comment]
+1

**Comment by javelinanddart** [comment]
Bump

**Comment by javelinanddart** [comment]
Removd 8X60 One, I pull req'ed it

**Comment by ZdrowyGosciu** [comment]
Bump :+1:

**Comment by Shoaib0597** [comment]
Any chances this will be merged?

**Comment by Shoaib0597** [comment]
Will this be merged? I have added Sultan's Simple Thermal in my kernel but it doesn't shows up in Thermal TAB. Is there any other app or modified KA available to control the thermal?

**Comment by javelinanddart** [comment]
It can't be merged, as its a feature request, not a pull request

**Comment by Shoaib0597** [comment]
Oh, my bad!
