### ISSUE TITLE
Fast Charge

### ISSUE THREAD

**Issue by SafinWasi** [Grarak/KernelAdiutor#2]
Would love the fast charge functionality.
Code for terminal:echo 1> /sys/kernel/fast_charge/force_fast charge

**Comment by Grarak** [comment]
Fastcharge is already there

https://github.com/Grarak/KernelAdiutor/commit/f4f30ea2554eb3cbb1c818ebfda830a506157044

**Comment by SafinWasi** [comment]
Right,sorry
