### ISSUE TITLE
Widget for Profile switching!

### ISSUE THREAD

**Issue by generalcool** [Grarak/KernelAdiutor#20]
Hi, first oft all awesome app!!!

I just found it today and till now all functions work great. Really really amazing, best CPU/kernel control app i tried and design is nice too! 10/10

However there is one feature im missing! The ability to set CPU frequency and governor (and multi core Option not to forget) make this an almost ideal battery saving app. Being able to save all settings in profiles, i made a performance and an energy saving profile.
Now it would be really awesome if i could quickly switch between the profiles! A simple widget would do the job. Having this in quick toggles would probably be even nicer, so you could acess it without returning to home screen, but i guess this would be more work to programm.

Thanks for sharing your awesome work!
-generalcool

**Comment by Grarak** [comment]
Added
https://github.com/Grarak/KernelAdiutor/commit/98b3026b8a49d3628db9799734c76d24eb885585
