### ISSUE TITLE
More Useful Profiles 

### ISSUE THREAD

**Issue by dgallagher33** [Grarak/KernelAdiutor#204]
Make it easier to change profiles. 
1. Make it compatible with Tasker so users can change performance profiles in certain situations. 
2. Use the new Cyanogenmod API to make a quick settings toggle in the pull down menu and allow users to customize which profiles it'll cycle through. 

Love the app, this would complete it for me

**Comment by Grarak** [comment]
tasker is already support?

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/1bc4dd8882ed5918439a03c22b27f0b707125d04
