### ISSUE TITLE
[Feature Request] Lock Settings

### ISSUE THREAD

**Issue by dryx01** [Grarak/KernelAdiutor#205]
I don't know if this request is already said, but I tell you anyway.
Some settings are modified by the system or by the mpdecision driver.
Can you add a option who is lock settings to prevent other factor to change the settings in our place? I know it is dangerous, but people using Kernel Adiutor know what they do, right?

sorry for my bad english

**Comment by Grarak** [comment]
Not possible.

**Comment by dryx01** [comment]
But trickster have do this, why not you ?

**Comment by Grarak** [comment]
What?

**Comment by Grarak** [comment]
Permission hack is already included if you mean this

**Comment by dryx01** [comment]
Where is it ?

**Comment by Grarak** [comment]
In the code?

**Comment by dryx01** [comment]
In the app. Because on all boot of my nexus 5, a part of settings does not be apply ( fast charge, CPU governor, and other things ).

**Comment by Grarak** [comment]
Check your logs. Apply on boot is working.

**Comment by dryx01** [comment]
OK. Thanks you.
