### ISSUE TITLE
Removed.

### ISSUE THREAD

**Issue by taiwraec** [Grarak/KernelAdiutor#207]
Removed.

**Comment by DespairFactor** [comment]
This is a stupid request

**Comment by taiwraec** [comment]
No it isn't. It's a shortcut to making the cpu hotplug in a different fashion. Kernel Adiutor currently doesn't let you change the NwNs or TwTs thresholds, while other Hotplugs such as Intelliplug have this feature like full mode profiles where they basically do the same thing with sysfs.

**Comment by javelinanddart** [comment]
This is a stupid request I have to agree.
If you want profiles, code the feature, expose it to sysfs, then add a request.
Trying to make profiles (especially for a specific feature) on the app side is infinitely more difficult than the doing it on the kernel side

**Comment by Electrex** [comment]
Yes, you should have asked me first before-hand.
