### ISSUE TITLE
cmSDK tile not enabling profiles

### ISSUE THREAD

**Issue by curiousercreative** [Grarak/KernelAdiutor#218]
The QS tiles shows up with the KA profiles listed, but tapping and double tapping a profile does nothing.

**Comment by curiousercreative** [comment]
I'm on 8/23 nightly CM12.1, Nexus 4, Quanta Kernel v6test3

**Comment by Grarak** [comment]
Are you on latest CM version?

**Comment by curiousercreative** [comment]
Yes, a nightly from a day or two ago, CM 12.1.

**Comment by curiousercreative** [comment]
Just installed CM 12.1 nightly 8/26 and the issue persists.

**Comment by Grarak** [comment]
Did you check your logcat? I just tested it works for me

**Comment by curiousercreative** [comment]
Still doesn't work for me (now on 8/28 nightly). I'm no exert expert at reading the logcat, but I don't see anything that looks related to KA. Care for a copy? What's your email?

**Comment by Grarak** [comment]
Just get the logcat and search for "Kernel Adiutor"

**Comment by curiousercreative** [comment]
Upon further inspection and testing, 1 out of 3 of my profiles work when applied through the QS tile and the logcat has entries only for the profile that works. The profile that works only applies "sound" settings (headphone poweramp gain). My other two profiles don't work when applied via QS tile (but do via profile widget or app) and they are both only applying "scren" setting for exponential/linear backlight mode. The logcat doesn't seem to have an entry for these at all.

**Comment by Grarak** [comment]
I created 5 different profiles. All of them got applied without problems.

**Comment by curiousercreative** [comment]
Upon further testing, the problem appears to only affect profiles that are toggling the same setting. To recreate the issue:
1. Create a first profile for applying one setting (Battery -> USB Fast Charge set to "on")
2. Create a second profile for only toggling the same setting (Battery -> USB Fast Charge set to "off"
3. Test that both profiles work by applying them through the KA app or KA home screen widget. They should work as expected, toggling the setting.
4.  Try to toggle between both profiles through the KA QS tile. Verify that you are unable to toggle between the profiles; neither profile may be applied or only one will apply but not the other.

I've tested this on my Nexus 4 running Quanta Kernel v6test3. Two profiles that toggle the "Screen -> LCD Backlight exponential brightness mode" setting results in neither profile applying while two profiles that toggle USB fast charge result in only one of the profiles applying but not the other.
