### ISSUE TITLE
Nexus 6 wakelock tunables

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#22]
I think I made mistake on the wakelocks.
Now the proper:

"smb135x wakelock" prevent wakelock when power disconnected
/sys/module/smb135x_charger/parameters/use_wlock

"sensor_ind wakelock" prevent wakelock when Ambient Display disabled
/sys/module/wakeup/parameters/enable_si_ws

(Y wakelock on or N wakelock offf)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/0e1ae55310a4f11e040a52ad25761e9a7f1b16c1

**Comment by engstk** [comment]
Thanks mate!
