### ISSUE TITLE
Native Double Tap-to-Wake Toggle for Armani (aka Xiaomi Redmi 1s)

### ISSUE THREAD

**Issue by Micky007** [Grarak/KernelAdiutor#223]
Hello grarak, can you add a Toggle in the Wake Device Controls section named "Native D2W"?The commands are
to enable 
echo 1 > /sys/bus/i2c/drivers/ft5x06_i2c/5-0038/d2w_switch
to disable 
echo 0 > /sys/bus/i2c/drivers/ft5x06_i2c/5-0038/d2w_switch
Native D2W is a feature of "TheBeast"  Kernel  by XDA user @Luffy.d,  more infos here http://forum.xda-developers.com/redmi-1s/orig-development/kernel-beast-kernel-t2998620

**Comment by Grarak** [comment]
added in beta
