### ISSUE TITLE
Extended profiling options/ widget enhancement

### ISSUE THREAD

**Issue by Mizanari3** [Grarak/KernelAdiutor#224]
Hello, I'm currently using the TMo LG G4, some report good battery life while others like myself are reporting horrible battery life... So of course I had the look into what really killing the battery, I've concluded that the it's the kernel and it's lack of an decent governor... The cores hardly never sleep they all run and occasionally out of the 6 only the 2nd big core goes to sleep... So I have created the widget with 3 profiles. 2 cores, 3 cores and 6 cores.... Im happy that the settings sticks and the core actually do stay off... This has gained me more than 50% of battery compaired to what I was getting before.. So I'm asking for an Screen off profile and indicators on the widget to show active profile and active number of cores online...

**Comment by Grarak** [comment]
please use other apps for that. Kernel Adiutor is not meant to monitor your device.
