### ISSUE TITLE
Lightweight JSON-based plugins

### ISSUE THREAD

**Issue by KOLANICH** [Grarak/KernelAdiutor#233]
How about plugins adding switches to KA? Most of kernels are managed through writing numbers into differrent pseudofiles. Maybe it is possible to store the info about these pseudofiles and ther values semantics in json files, dynamically create UI widgets and write values into pseudofiles on changes in the widgets' values?

**Comment by JeseChan** [comment]
It would be great if can compatible with Synapse's JSON-based files.

**Comment by Grarak** [comment]
custom controls kinda does that. No UCI planned.
