### ISSUE TITLE
Some new features :-)

### ISSUE THREAD

**Issue by captainjjjacksparrow** [Grarak/KernelAdiutor#244]
Hello. I would like to give you some new features requests :

1. Wipe battery stats 
2. Wipe dalvik cache
3. Wipe cache
4. Change IMEI
5. Change MAC adress 
6. Soft Reboot mode

For additional informations, you can contact me on captainjjjacksparrow@yahoo.com
Thank you again for this very useful app. :D

**Comment by Grarak** [comment]
1. download a wipe battery states app
2. recovery section
3. recovery section
4. not possible
5. not possible
6. won't add
