### ISSUE TITLE
Bluetooth Mouse buttons mapping

### ISSUE THREAD

**Issue by corb06** [Grarak/KernelAdiutor#246]
Not sure if it's Kernel based, but I would like to map my Bluetooth Mouse Right button to Back button function. 
I would also like to program my middle mouse button to behave like the Tablet Home Button. 

Is this possible?
It would be awesome with this, so that we don't have to press the tablet back button all the time when we want to go backwards. 

Tab S 10.5 with Slim LP Rom.

**Comment by Grarak** [comment]
key mapping is handled by frameworks. can't change that.
