### ISSUE TITLE
Overwrite profile

### ISSUE THREAD

**Issue by jukov** [Grarak/KernelAdiutor#247]
Hi guys, I have an idea.
I want to add to profile menu button for overwrite profile. This can be useful when setting up the voltage when the profiles are frequently overwritten.
Do you think you need this feature?
![screenshot_2015-10-06-18-37-27](https://cloud.githubusercontent.com/assets/8081721/10308713/7a13d5f4-6c59-11e5-9096-c0144dc2bea7.png)

**Comment by Grarak** [comment]
added
