### ISSUE TITLE
IO Scheduler Settings not workin on Samsung Galaxy S6

### ISSUE THREAD

**Issue by tpoint75** [Grarak/KernelAdiutor#248]
We don't have:
/sys/block/mmcblk0
/sys/block/mmcblk1

but we have:
/sys/block/sda
/sys/block/sdb
/sys/block/sdc

https://github.com/Grarak/KernelAdiutor/blob/master/app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java#L565

**Comment by Grarak** [comment]
should be in the beta

**Comment by tpoint75** [comment]
Works! Thank you!

Willi Ye <notifications@github.com> schrieb am Mo., 1. Aug. 2016, 18:35:
