### ISSUE TITLE
wake controls nexus 5

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#25]
"set DT2W"
/sys/android_touch/doubletap2wake (0 disabled, 1 enabled halfscreen, 2 enabled fullscreen)

"Set wake timeout"
/sys/android_touch/wake_timeout (int timer in minutes, 0 is disabled)

"Use power key suspend override"
/sys/module/qpnp_power_on/parameters/pwrkey_suspend (0 disabled, 1 enabled)

**Comment by Grarak** [comment]
Added
https://github.com/Grarak/KernelAdiutor/commit/e95d8861c8539e626ad4ea39e91b94418ea0bf74

**Comment by engstk** [comment]
thanks mate
