### ISSUE TITLE
CAF adaptive LMK tunables

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#252]
/\* User knob to enable/disable adaptive lmk feature */
/sys/module/lowmemorykiller/parameters/enable_adaptive_lmk (on/off: 1/0 switch)

/*
  This parameter controls the behaviour of LMK when vmpressure is in
  the range of 90-94. Adaptive lmk triggers based on number of file
  pages wrt vmpressure_file_min, when vmpressure is in the range of
  90-94. Usually this is a pseudo minfree value, higher than the
  highest configured value in minfree array.
 */
/sys/module/lowmemorykiller/parameters/vmpressure_file_min (int default 53059 for > 2GB devices)

**Comment by javelinanddart** [comment]
https://github.com/Grarak/KernelAdiutor/commit/eb5581c9cf609ef640abb58f1c2fb910e5a92fac
Isn't this it?

**Comment by Tsunamical** [comment]
That commit just has the toggle, not the vmpressure commands
