### ISSUE TITLE
Nexus 6 msm_hsic_host wakelock

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#26]
"msm_hsic_host wakelock" prevent msm_hsic_host wakelock
/sys/module/wakeup/parameters/enable_msm_hsic_ws (Y wakelock on or N wakelock off)

**Comment by Grarak** [comment]
It's already done
https://github.com/Grarak/KernelAdiutor/issues/22

**Comment by engstk** [comment]
Thanks mate

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/c69580ceac7641fd9d6d6f853905963fa76ba03c

**Comment by engstk** [comment]
thanks mate
