### ISSUE TITLE
TCP Congestion Settings Not Showing

### ISSUE THREAD

**Issue by Tsunamical** [Grarak/KernelAdiutor#260]
TCP Congestion Settings don't show when used with my G2 kernel. They will show when switching through terminal, however they don't show in the app. My kernel is built with -O3 and SM 5.1, I believe the issue may have started occurring when I switched to said build conditions. They have also disappeared from Synapse.

**Comment by Grarak** [comment]
cat /proc/sys/net/ipv4/tcp_available_congestion_control please

**Comment by Tsunamical** [comment]
I've since switched back to default CM kernel, and the issue is no longer present. I believe it was due to an issue within my kernel. Closing this as there's no reason it should be related to KernelAdiutor.
