### ISSUE TITLE
Native Double Tap to Wake for Nexus 6P

### ISSUE THREAD

**Issue by DespairFactor** [Grarak/KernelAdiutor#271]
DT2W sysfs path:
/sys/devices/soc.0/f9924000.i2c/i2c-2/2-0070/input/input0/wake_gesture
Default value(disabled): 0
enable value: 1

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/52accf84a8391abef9bc8d01aa2104bb7e1a2ab0
