### ISSUE TITLE
Cannot disable some CPU cores on Moto X Play

### ISSUE THREAD

**Issue by roberth1990** [Grarak/KernelAdiutor#275]
When I disable all the LITTLE cores on my Moto X Play, after a while, the first of the LITTLE cores goes online again after going into the other categories or exiting the app.

**Comment by roberth1990** [comment]
That issue seem to have at least temporarily disappeared, but I have also had issue with the third big core going offline and not being able make it go online.

Both of the issues disappeared when I modified the minimum and maximum frequency.

**Comment by Grarak** [comment]
disabling cores got removed in the beta
