### ISSUE TITLE
Apply on boot option of selinux-plugin not working.

### ISSUE THREAD

**Issue by ageback** [Grarak/KernelAdiutor#276]
I'm not sure if this is the right place to report this issue. Maybe I shoud report in selinux-plugin repository. If I'm wrong please correct me.

I installed the selinux changer plugin and I want to change it to Permissive on boot. But the ApplyOnBoot option not working. When rebooting it remains off and sulinux is Enforce.

**Comment by Tsunamical** [comment]
+1

**Comment by nobe1976** [comment]
That mostly has to do with a build prop that most ROMs have in it. Look for to.build.selinux=1 and change the value to 0 and reboot.

**Comment by yoinx** [comment]
https://github.com/Grarak/KernelAdiutor/pull/367

**Comment by Grarak** [comment]
plugins got replaced by custom controls, which should work
