### ISSUE TITLE
Plugin: Getting list of options provided by kernel 

### ISSUE THREAD

**Issue by wingoku** [Grarak/KernelAdiutor#278]
@Grarak Can you provide a documentation or insight about how can I access the options supported by a kernel that's interfaced with kernel adiutor? I have read the code for the plugin library, inside the PluginManager.class, the API provides a method to execute certain commands. The only thing I want to know, how would the plugin know which commands are available so that they can be toggled via a plugin.

**Comment by Grarak** [comment]
plugins got replaced by custom controls.
