### ISSUE TITLE
Nexus 5 LCD dimmer controls

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#28]
"Set backlight dimmmer"
/sys/module/lm3630_bl/parameters/backlight_dimmer (Y enable, N disabled)

"Dimmer level"
/sys/module/lm3630_bl/parameters/min_brightness (int 1~10)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/5f35621116c478f29925d40529e43faa4b63cc3e

**Comment by engstk** [comment]
thanks mate
