### ISSUE TITLE
Suggestions - change dpi

### ISSUE THREAD

**Issue by ReSearchITEng** [Grarak/KernelAdiutor#282]
it would be nice to have a gui interface for changing this, ideally witj some sample text next to it and a note whet it reaches the tablet mode.
the command to change it is: 
 wm density <value>

**Comment by Pafcholini** [comment]
You have the build.prop tab and there you can change the dpi.

**Comment by ReSearchITEng** [comment]
that is correct. it can be done also via the command line I've put above (without reboot).
 I suggested to have a gui method of changing it, in kerneladiutor.

**Comment by Tsunamical** [comment]
Some ROMs gave this option already :)

**Comment by ReSearchITEng** [comment]
could be, but for the majority of us, it would be nice.
just a suggestion.:)

**Comment by cosmicdan** [comment]
Just my opinion, I wouldn't like this. We have many GUI build prop editors already, such a thing seems outside the scope of a Kernel related app.

Maybe as an optional/official plugin, though, sure. But for many of us, we'd prefer to see Adiutor stay lean and specific to kernel stuff.

**Comment by DespairFactor** [comment]
Can we have a new feature for skull density? Seems some people don't get the concept of duplicating work

**Comment by cosmicdan** [comment]
Wtf? Is it really necessary to throw personal insults? You could have just said you agree to my point instead of calling him stupid.

**Comment by DespairFactor** [comment]
I see some people have a poor sense of humour
