### ISSUE TITLE
Hide icon in app drawer when imbedded

### ISSUE THREAD

**Issue by nobe1976** [Grarak/KernelAdiutor#283]
Kinda like SuperSu does. This by far one of the most useful apps that is out there. Great features and interface. Adding it to a custom Rom settings without seeing it in the app drawer would make it even better. 
Awesome work man. 
Thanks in Advance.

**Comment by Mazda--** [comment]
I agree, this would make it less redundant for custom ROMs to include Kernel Adiutor within settings

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/e4eed9618a7d53bf9142699aa99df2f80f2ad7d2

**Comment by Grarak** [comment]
put ro.kerneladiutor.hide=true to build.prop
