### ISSUE TITLE
sweep2wake: S2S Only Sysfs Issue

### ISSUE THREAD

**Issue by javelinanddart** [Grarak/KernelAdiutor#285]
Can you combine the sweep2wake sysfs and s2w_s2sonly into a card that you can choose between both and just sweep2sleep? I know you have that card somewhere, but this is the proper way to do it, it's what the mainline s2w sysfs from @showp1984 is expecting

**Comment by javelinanddart** [comment]
Currently if s2w_s2sonly Sysfs is present, It calls it disabled when that sysfs is off
"Enabling" S2W with that card effectively enables Sweep2Sleep Only, but this is completely broke logic, and dumb
This is not how it is supposed to work

**Comment by showp1984** [comment]
Actually it is exactly how it is supposed to work. It's an override switch which allows only s2s to work.
I don't see how this is broken. It was once a debug setting, but ppl liked it and so I patched it back in.
There probably should be one single sysfs endpoint to handle this and simplify things, but it currently works just fine.

**Comment by javelinanddart** [comment]
There's two different places you can set S2S only (or at least there was at the time)
