### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by aul12** [Grarak/KernelAdiutor#29]
When i apply a profile which is already set via the widget the app chrashes and I can't use the widget until I reopen the app.
HTC one s, cm 12 (lollipop)
Logcat when I'm at home

**Comment by aul12** [comment]
02-16 14:01:32.987 E/AndroidRuntime(18465): java.lang.RuntimeException: Unable to start receiver com.grarak.kerneladiutor.widgets.ProfileWidget: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference

**Comment by Grarak** [comment]
Try to clear app data

**Comment by aul12** [comment]
Thanks for the fast fix!
