### ISSUE TITLE
KCAL - Advanced color control

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#30]
Here's the tunables:

/sys/devices/platform/kcal_ctrl.0/kcal - (0-256 0-256 0-256) - Controls Red/Green/Blue Multipliers
/sys/devices/platform/kcal_ctrl.0/kcal_min - (0-256) - Controls minimum RGB Multiplier value
/sys/devices/platform/kcal_ctrl.0/kcal_enable - (0-1) - Enables/Disables RGB Multiplier Control
/sys/devices/platform/kcal_ctrl.0/kcal_invert - (0-1) - Enables/Disables Display Inversion Mode
/sys/devices/platform/kcal_ctrl.0/kcal_sat - (224-383 or 128) - Controls saturation intensity - use 128 for grayscale mode
/sys/devices/platform/kcal_ctrl.0/kcal_hue - (0-1536) - Controls display hue - may have issues with msm8x26 in the higher values
/sys/devices/platform/kcal_ctrl.0/kcal_val - (128-383) - Controls display value
/sys/devices/platform/kcal_ctrl.0/kcal_cont - (128-383) - Controls display contrast

You can check app layout made by savoca:
https://www.youtube.com/watch?v=FSgPUN05I90

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/67980782e84d73789c5450c8360d45dee20fb248

**Comment by engstk** [comment]
thanks mate
