### ISSUE TITLE
Scaling of the usage card on smaller devices

### ISSUE THREAD

**Issue by deadman96385** [Grarak/KernelAdiutor#33]
Larger phones it looks normal, but on smaller phones like the s3 it looks bad this commit should fix it
https://github.com/deadman96385/android_packages_apps_KernelAuditor/commit/eb2e89c25fadf3c35ab6849d341baae76f588bce

![befor after](https://cloud.githubusercontent.com/assets/2042793/6386460/738b0358-bd3e-11e4-8460-088ad0121f9d.jpg)

**Comment by Grarak** [comment]
I'm not sure about this. Are you using a custom lcd.density? Because the app won't split up the cards on phones.

**Comment by zimlokks** [comment]
What rom are you using, android version. Itll help the dev out fix it quicker.

**Comment by deadman96385** [comment]
Nah he is right it has to do with my custom DPI, personally I think it looks better with a smaller card though. I'll just keep it on my Liquidsmooth fork.
