### ISSUE TITLE
Feature request: Import/export profiles

### ISSUE THREAD

**Issue by flocke** [Grarak/KernelAdiutor#330]
As the title says, it would be nice to have the option to export single (or multiple) profiles into a file (JSON would probably be best/simplest) which can then be imported again later/on a different phone.
This would make it very easy to share them with other users and keep them when switching ROMs (without always having to copy the profiles.json file manually).

**Comment by msakallah** [comment]
Also, it would be nice if it can be modified outside of the application (for example on a pc or an editor) and then imported. I noticed that if I edit the file then save, it's no longer recognized

**Comment by Grarak** [comment]
Added in beta
