### ISSUE TITLE
Add BCL options

### ISSUE THREAD

**Issue by APOPHIS9283** [Grarak/KernelAdiutor#346]
https://github.com/team-vortex/SINGULARITY-UKM/commit/64517ab836233132647dcb132a0424ba1e18cb2b

**Comment by APOPHIS9283** [comment]
`if [ -d "/sys/module/battery_current_limit/parameters" ]; then
				$BB echo '{ SPane:{
					title:"BCL Options",
					description:"Various options for Battery Current Limiting",
				}},'
				if [ -f "/sys/module/battery_current_limit/parameters/bcl_user_enable" ]; then
				BCL=\`$BB cat /sys/module/battery_current_limit/parameters/bcl_user_enable\`
					{ SCheckBox:{
						label:"Enable BCL",
						description:"Disable BCL completely.",
						default:'$BCL',
						action:"generic /sys/module/battery_current_limit/parameters/bcl_hotplug_enable"
					}},'
					}},'
				fi
				if [ -f "/sys/module/battery_current_limit/parameters/bcl_hotplug_enable" ]; then
				BCLHP=\`$BB cat /sys/module/battery_current_limit/parameters/bcl_hotplug_enable\`
					{ SCheckBox:{
						label:"Enable Hotplugging",
						description:"Disable BCL Hotplugging.",
						default:'$BCLHP',
						action:"generic /sys/module/battery_current_limit/parameters/bcl_hotplug_enable"
					}},'
					}},'
				fi
			fi`

**Comment by Grarak** [comment]
Won't happen
bcl is auto controlled by KA
