### ISSUE TITLE
add sweep2wake triggers for android one devices

### ISSUE THREAD

**Issue by wazeeahmed** [Grarak/KernelAdiutor#348]
kernel aduitor can't turn on sweep2wake even if my kernel supports it . sysfs path is /sys/android_touch/sweep2wake . please add it .

**Comment by yoinx** [comment]
I'm not sure this is the best way to fix this.... 

But lets face it, it's just allowing an app to detect the various wake gestures... just turn them all on. 

https://github.com/Grarak/KernelAdiutor/pull/366
