### ISSUE TITLE
Fix cpu input freq did not work for me

### ISSUE THREAD

**Issue by bhb27** [Grarak/KernelAdiutor#352]
https://github.com/Grarak/KernelAdiutor/commit/9cc880035251cd7d47de13a9f1ff7f330bebc4d0

That commit is not working on my device.

The app can set the input freq to it core, but it can't save and when I reboot it only load the input freq to the last core that I change.

I did a test, I clean the app, and change only the 4 clock input freq, and check the profile, and there there is only the last one that I change on the file.

echo 1:freq > sys/module...

If i revert the commit it works

and it show on profile

echo 0:freq 1:freq 2:freq 3:freq > sys/module...

Again this doesn't stops the app to set the freq to it core, just the ability to save on profile and set at boot.

**Comment by yoinx** [comment]
I get the same thing on shamu. 

This commit fixes it as well.  Not really sure if it breaks anything though for other devices.
https://github.com/Grarak/KernelAdiutor/pull/363

**Comment by bhb27** [comment]
:+1: 
Yes that did it.

Sorry for the delay on a answer, very busy and git didn't send me a warning.

BTW nice work on the app, I will try to port some of yours commit, to better support my kernel thanks.

BCL, building SE Linux and Gaming mode is really nice.

weird my BCL folder is qcom,bcl.38...

**Comment by yoinx** [comment]
Interesting I wonder what the bcl.xx is and what values are out there....
