### ISSUE TITLE
Request msm_limiter enable/disable toggle

### ISSUE THREAD

**Issue by bhb27** [Grarak/KernelAdiutor#353]
Does any one ever did this and can share the code/commit?

If not, can someone make a simple toggle to enable disable the option?

UKM/Synapse have a implementation but I don't know how to port.

Here are the files if some one can see and do...

kernel files:
https://github.com/neobuddy89/shamu/blob/marshmallow/drivers/soc/qcom/msm_limiter.c
https://github.com/neobuddy89/shamu/blob/marshmallow/include/soc/qcom/limiter.h

UKM
https://github.com/apbaxel/UKM/blob/UKM-Enhanced/data/UKM/config.json.generate.cpu
a commit that have the code...
https://github.com/apbaxel/UKM/commit/5463095afa53f38aec19cec8bcb826c55483f9c2

Thanks.

**Comment by yoinx** [comment]
I've actually already done this. 

See Pull request: https://github.com/Grarak/KernelAdiutor/pull/360
