### ISSUE TITLE
Fsync status misreading

### ISSUE THREAD

**Issue by dirty-hank** [Grarak/KernelAdiutor#356]
Some Fsync enable/disable implementations use Y/N instead of 1/0. I think Kernel Adiutor expects numeric input and somehow misbehaves on such implementations.

**Comment by Tsunamical** [comment]
Known issue

**Comment by yoinx** [comment]
Seems like a simple fix... just make the return statement check if .equals("1") or .equals("Y") return true, else return false. 

On the set side of the house, moduleparam fixes it from 1 to Y, if that's what it expects....

**Comment by Grarak** [comment]
Fixed in beta
