### ISSUE TITLE
I want Voltage Control Feature for Exynos Soc.

### ISSUE THREAD

**Issue by ghost** [Grarak/KernelAdiutor#358]
Hi, I'm using Exynos Devices. I added voltage control commit to my kernel, but there is not cpu voltage menu in your app. I can use synapse instead, but i prefer your application more. What I want is please add voltage control feature for exynos soc. I'm using Exynos 5430 (Samsung Galaxy Alpha) 
Thank you for reading my issue.
Sincerely, Kitakami

**Comment by DerRomtester** [comment]
sysfs path would be helpful

**Comment by Grarak** [comment]
Closed until path is provided
