### ISSUE TITLE
add an option to control when lmk kills when swap is being used

### ISSUE THREAD

**Issue by USBhost** [Grarak/KernelAdiutor#359]
https://github.com/USBhost/FIRE-ICE/commit/9875745420d1bf617749e60953c1fd308b79f38a

It would be nice if you could supported it
If not don't worry :)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/d120800bfd2fa5463b7f5e268b6bb80fb58f21f1
