### ISSUE TITLE
CPU Boost Toggle

### ISSUE THREAD

**Issue by yoinx** [Grarak/KernelAdiutor#362]
https://github.com/Grarak/KernelAdiutor/pull/361

the CPU boost frequency accepts 'core:value core:value core:value' up to all cores or 'specific_core:value' to update just one core

Unfortunately, the apply on boot json is only saving the last command run for the path. To work-around this, we'll just send the full list of updated values each time.

**Comment by Grarak** [comment]
Fixed in beta
