### ISSUE TITLE
CPU tab not accessible

### ISSUE THREAD

**Issue by benschhold** [Grarak/KernelAdiutor#368]
Seems CPU tab is doesnt open and load forever when big cores are shutdown because of low battery for example.
Device OnePlus2

**Comment by yoinx** [comment]
Do you have a logcat for it?  I imagine that something in there might be useful.

**Comment by benschhold** [comment]
in logcat it stays stuck at "loading governors"

**Comment by utack** [comment]
I have this too on Nexus 5X.
Will try to properly logcat it next time I heat up the phone

**Comment by Grarak** [comment]
Fixed in beta
