### ISSUE TITLE
KernelAdiutor "forgets" settings

### ISSUE THREAD

**Issue by ppawel** [Grarak/KernelAdiutor#372]
This happened to me two or three times already in the last month and I'm not sure what is the problem.

Basically, I customized some CPU and CPU Hotplug settings, enabled "set on boot" for those sections and all was fine. Today I noticed that all settings (e.g. governor, hotplug, frequencies) have been reset to ROM defaults - governor to interactive instead of intelimm, hotplug to mpdecision instead of intelliplug etc. I have not flashed new ROM updates or anything since I last set configuration in KernelAdiutor.

Any suggestions how to diagnose this problem?

For reference, the phone is Samsung S4 Mini (I9195), ROM is Android 6.0.1 (ResurrectionRemix 5.6.3 to be exact).

**Comment by d0x360** [comment]
I have the same issue, nexus 6 pure nexus

**Comment by ppawel** [comment]
OK, I think my problem was that I was using Greenify to kill Kernel Adiutor and it was not able to apply settings at startup. Now it seems to be working.
