### ISSUE TITLE
Sweep2Wake and Sweep2Sleep Mixup

### ISSUE THREAD

**Issue by dirty-hank** [Grarak/KernelAdiutor#373]
When Sweep2Wake and Sweep2Sleep sysfs files are present (/sys/android_touch/sweep2wake and /sys/android_touch/s2w_s2sonly respectively) KernelAuditor displays the Sweep2Wake card on the "Wake Controls" tab but when Enabled/Disabled is selected it writes 1/0 to the wrong file (s2w_s2sonly instead of the correct sweep2wake).

**Comment by Grarak** [comment]
should be fixed in the beta
