### ISSUE TITLE
Request: add squid kernel's min_online_cpus for intelli_plug support

### ISSUE THREAD

**Issue by sm4tik** [Grarak/KernelAdiutor#375]
https://github.com/sultanqasim/android_kernel_motorola_msm8916/commit/0c0a1c6ebe86f56145e48ea7e47f5461a4cf6b11

echo num > /sys/module/intelli_plug/parameters/min_online_cpus

**Comment by Shoaib0597** [comment]
Any chance of this one getting merged?

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/a1e2dc8f39b7c7d5315e5fa454741755058b1206
