### ISSUE TITLE
leds-qpnp: Battery/Notification LED control

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#376]
SysFS interface :

*  /sys/class/leds/red/device/led_fade (rw)

0 : blink
1 : fade (default)

*  /sys/class/leds/red/device/led_intensity (rw)

0 : stock intensity
1-100 : 0% to 100% of stock intensity
Note: Does only work for static led, not fading/blinking !!!

*  /sys/class/leds/red/device/led_speed (rw)

0 : stock speed
1 : continuous notification light
2-20 : 2 = very slow to 20 = very fast

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/bdcd50a7ba7057fb376fa9194a0c8f5e087a6f87
