### ISSUE TITLE
Screen option.

### ISSUE THREAD

**Issue by MatheusViGo** [Grarak/KernelAdiutor#383]
The high brightness option in Moto G 2014 ( Cyanogenmod 13) off alone after a while.
#option enabled
[dmesg.txt](https://github.com/Grarak/KernelAdiutor/files/164201/dmesg.txt)
[last_kmsg.txt](https://github.com/Grarak/KernelAdiutor/files/164202/last_kmsg.txt)
[logcat.txt](https://github.com/Grarak/KernelAdiutor/files/164203/logcat.txt)
#Option disabled
[dmesg.txt](https://github.com/Grarak/KernelAdiutor/files/164205/dmesg.txt)
[last_kmsg.txt](https://github.com/Grarak/KernelAdiutor/files/164206/last_kmsg.txt)
[logcat.txt](https://github.com/Grarak/KernelAdiutor/files/164207/logcat.txt)

**Comment by Grarak** [comment]
CM handles hbm itself. Can't fix that
