### ISSUE TITLE
Trimming (fstrim)

### ISSUE THREAD

**Issue by AlbazA** [Grarak/KernelAdiutor#389]
Would love to see a Trimming feature added! You can incorporate the fstrim utility , as it's already a part of the Linux kernel

Options such as 
auto trim==>
trimming schedule 
Frequency
Time

Would be appreciated as well 

Cheers,
A.albaz

**Comment by Tsunamical** [comment]
Android apparently does this automatically, but not as often. Will look into this though.

**Comment by yoinx** [comment]
No. 

People need to stop force trimming their flash memory.  It just causes unneeded write cycles on their devices,  resulting in unneeded wear. 

I'm not sure when this "optimization"  began...  But it needs to stop.  Android runs trim when needed,  but running it more often you just eat away at the finite wrote cycles of your memory for no reason.

**Comment by Startrek852** [comment]
@Tsunamical you do NOT want to upgrade a 2012 Nexus 7 to stock Lollipop. It kills the tablet, making it completely unusable.

**Comment by Tsunamical** [comment]
Even so, still an incredibly small use case and TRIM still DOES run pre-Lollipop, just not as often.

**Comment by Grarak** [comment]
see @Tsunamical posts, closed!
