### ISSUE TITLE
Stop turning off and on cores when not required

### ISSUE THREAD

**Issue by Magissia** [Grarak/KernelAdiutor#392]
When changing core frequency, kernel adiutor is putting offline secondary cores to bring them on at the end of the operation, on Tegra2 SoC it cause the device to reboot. Please don't turn off cores when not required. (Don't know if changing frequencies from the interface cause this, but loading a profile do have this behavior, when looking at CPU profiles commands, you clearly see it shutting down cores to turn them on again at the almost end. )

**Comment by Waester** [comment]
Sounds like you have some sort of CPU Hotplug enabled. Try to disable mpdecision or any CPU hotplug features.

**Comment by Grarak** [comment]
shouldn't happen. please try the beta, if this problem still persists, please reopen
