### ISSUE TITLE
Support Tegra 2 voltage table

### ISSUE THREAD

**Issue by Magissia** [Grarak/KernelAdiutor#395]
Hello, looks like kernel adiutor doesn't support Tegra 2 voltage table, it is located here for Tegra 2 devices: /sys/devices/system/cpu/cpu0/cpufreq/frequency_voltage_table

Here's an example of voltage table I took from my device: 

1640000 1475 1475
1600000 1450 1450
1504000 1425 1425
1400000 1350 1350
1200000 1275 1275
1000000 1100 1100
960000 1000 1000
798000 950 950
655000 875 875
503000 850 850
503000 800 800
380000 775 775
380000 775 775

**Comment by Grarak** [comment]
how to apply new values?

**Comment by Grarak** [comment]
closed until descriptions are given
