### ISSUE TITLE
Vibration Strength setting is not applied on startup

### ISSUE THREAD

**Issue by YoDevil** [Grarak/KernelAdiutor#396]

**Comment by Tsunamical** [comment]
What device? What's the vibration sysfs path for your device?

**Comment by YoDevil** [comment]
I'm on an LG G2 running a cm based custom rom. I don't know the path, but I don't think the problem lays there: I can change the vibration, but it gets back to default on reboot, even if I have the option to apply Misc controls on boot enabled.

**Comment by YoDevil** [comment]
Actually, I just found out that that it won't work neither by applying a saved profile.

**Comment by Primokorn** [comment]
Same issue here with a Nexus 5, the vibration strenght is reset at boot (Apply at boot checked in KA 0.9.9.3 or 0.9.9.4).

No problem with a su.d script to set the vibration strenght to 95% (/sys/class/timed_output/vibrator/amp).

**Comment by jdhedden** [comment]
Same issue on Nexus 6P.  Control file is /sys/class/timed_output/vibrator/vmax_mv_strong.  I set vibration strength to 25%, and the file is updated with 977 for the value.  I have "Apply on boot" set "on" with notification and toast "on" to verify.   On a "hot boot", the value remains at 25%/977.  On full reboot, the value in the file is reset to 1800 (49%) even though the notifications and toast report that "Apply on boot" service ran.

**Comment by Grarak** [comment]
Should work with beta
