### ISSUE TITLE
Sound Profiles

### ISSUE THREAD

**Issue by Android-Mailson** [Grarak/KernelAdiutor#4]
May have the option of "sound profiles" compatible with various kernel ... eg faux, hybrid and other ... would be great if it had

**Comment by Grarak** [comment]
If you could give me the paths of them then sure.

**Comment by Android-Mailson** [comment]
Hybrid  - https://github.com/neobuddy89/hammerhead/commits/lollipop/

Faux - https://github.com/faux123/Nexus_5

**Comment by Grarak** [comment]
I've added Faux Sound controls in version 0.6
If you still have problems just open a new issue

**Comment by Android-Mailson** [comment]
OK! Thanks for add ..
