### ISSUE TITLE
Curioso

### ISSUE THREAD

**Issue by pjpm1000** [Grarak/KernelAdiutor#401]
Eu gostaria do recurso de 'som'. Muito obrigado.

**Comment by Tsunamical** [comment]
Olá. Esta função é apenas para bugs ou erros no programa. Ele se destina a ajudar o desenvolvedor a resolver problemas com o programa. você pode fechar os "problemas"? Estou certo Grarak é feliz em saber que você está feliz :)

**Comment by Grarak** [comment]
I don't speak spanish(?)
