### ISSUE TITLE
Fauxsound for moto g

### ISSUE THREAD

**Issue by M0Rf30** [Grarak/KernelAdiutor#402]
Hi,
 on my moto g 2013 (falcon) fauxsound value are always resetted and poweramp slider return no supported values.
I've dumped the values setted from official FauxSound app for headphones and for every preset:

Quiet preset: Poweramp 40 40;  Headphones 251 251;  Speaker 253 253
Quality preset: Poweramp 33 33;  Headphones 254 254;  Speaker  254 254
Loudness preset: Poweramp 35 35;  Headphones 9 9;  Speaker 5 5
Stock preset: Poweramp 38 38;  Headphones 0 0;  Speaker 0 0

I report also min and max values as dumped on sys interface and as reported on Fauxsound slider:
headphones: Max 20 20 (20);  Min 226 226 (-30)
poweramp: Max 32 32 (6);  Min 44 44 (-6)
speaker: Max 20 20 (20);  Min 226 226 (-30)

Could you resolve this issue and add presets support ?
Thanks in advance
Greetings

**Comment by DerRomtester** [comment]
Is there a poweramp slider in kernel adiutor ? 
Poweramp and kernel adiutor are two different apps right ? 
Does it work with the original faux sound app? 
Have you tried to set the values manually with the echo command inside the terminal ? 
What kernel are you currently running ? (maybe your developer made a mistake)

**Comment by Tsunamical** [comment]
Not a developer mistake, the implementation here is indeedpoor and needs work. It's likely trying to read and write to incorrect paths.

**Comment by Tsunamical** [comment]
I'll give it a look shortly, I had the same issue when I had faux sound control in my kernel but I just overlooked it. It could be version dependent as well. I was on a modified version of 3.6.

**Comment by M0Rf30** [comment]
I've always had this issue, with stock and aosp based rom, original and custom kernel.
I've tried this script made by me but nothing
`#!/system/bin/sh
echo "0" > /sys/kernel/sound_control_3/gpl_sound_control_locked;

# Quality preset
echo "33 33" > /sys/kernel/sound_control_3/gpl_headphone_pa_gain;
echo "254 254" > /sys/kernel/sound_control_3/gpl_headphone_gain;
echo "254 254" > /sys/kernel/sound_control_3/gpl_speaker_gain;

# Quiet preset
#echo "40 40" > /sys/kernel/sound_control_3/gpl_headphone_pa_gain
#echo "251 251" > /sys/kernel/sound_control_3/gpl_headphone_gain
#echo "253 253" > /sys/kernel/sound_control_3/gpl_speaker_gain

# Loudness preset
#echo "35 35" > /sys/kernel/sound_control_3/gpl_headphone_pa_gain
#echo "9 9" > /sys/kernel/sound_control_3/gpl_headphone_gain
#echo "5 5" > /sys/kernel/sound_control_3/gpl_speaker_gain

# Stock preset
#echo "38 38" > /sys/kernel/sound_control_3/gpl_headphone_pa_gain
#echo "0 0" > /sys/kernel/sound_control_3/gpl_headphone_gain
#echo "0 0" > /sys/kernel/sound_control_3/gpl_speaker_gain

echo "1" > /sys/kernel/sound_control_3/gpl_sound_control_locked;
`

**Comment by Kamin4ri** [comment]
Apparently the sound control driver needs to calculate a bloody checksum before setting the values.

`static bool calc_checksum(unsigned int a, unsigned int b, unsigned int c)
{
	unsigned char chksum = 0;

	chksum = ~((a & 0xff) + (b & 0xff));

	if (chksum == (c & 0xff)) {
		return true;
	} else {
		return false;
	}
}`

**Comment by M0Rf30** [comment]
Any  chance to integrate the kamin4ri work on tpa6165 in ka?

**Comment by Kamin4ri** [comment]
I sent a PR already (sent a new one because i royally screwed things up in my last PR). Waiting for grarak to merge it.

Oh, and KA knows how to calculate that bloody checksum. So forget that C code snippet posted above.

**Comment by M0Rf30** [comment]
Thank you man
