### ISSUE TITLE
BLN

### ISSUE THREAD

**Issue by kularny** [Grarak/KernelAdiutor#403]
I recently added bln support for i9100

http://review.cyanogenmod.org/#/c/143238/
http://review.cyanogenmod.org/#/c/143878/

It needs this app.
https://play.google.com/store/apps/details?id=neldar.bln.control.free

But the problem is that it doesnt ask for root...and it gives a denial for untrustedapp scontext...We can bypass it...but can u plz add the support.

That app asks the path from lights.c
/sys/class/misc/backlightnotification/notification_led

It would really be helpful if u add this feature back. Thanks.

**Comment by Tsunamical** [comment]
Asking on a commit for him to add this feature is not a good idea. You are not entitled to have this written into the app as such. Grarak is currently busy with the rewrite, so additional features are likely lower on the priority scale, and this is only applicable to so many devices, hence why not many people know of the feature.

If you would like someone else to pick it up, provide more information about the sysfs path (what it does, what values are accepted, etc), that way it is easier for a stranger to pick it up. If you could add those commits to the kernel, I'm sure you can figure out the Java to add to this, as most of it is just duplication anywho.

**Comment by kularny** [comment]
First iam not entitiled... 2nd I can do them in java,,,I just needed a common app...btw this feature was already there in the past.

**Comment by Grarak** [comment]
bln is something that lights hal handles, won't mess with that.
