### ISSUE TITLE
Profile -> Per App Settings Force Close

### ISSUE THREAD

**Issue by killer23d** [Grarak/KernelAdiutor#407]
[logcat.txt](https://github.com/Grarak/KernelAdiutor/files/320916/logcat.txt)
I am using BlissPop 6.4 (CM13 based) with language changed to Chinese. When I loaded a profile and tried to choose Per App, the app just force quit. Using 0.9.9.3 build 13.

Included the log cat and it is showing in time 09:11:52 where the crashed happened.

I hope this an help the future development of the great app.

**Comment by huu00000** [comment]
issue

**Comment by huu00000** [comment]
issue

**Comment by Grarak** [comment]
Per app settings does not even exist
