### ISSUE TITLE
Mediatek Helio X10 support

### ISSUE THREAD

**Issue by jerryshaw12** [Grarak/KernelAdiutor#409]
Please add support to helio x10 i am unable to adjust governor value with this app, also helio x10 IS NOT BIG.LITTLE processor architecture

**Comment by Grarak** [comment]
Send me the build.prop
Am 28.06.2016 13:47 schrieb "jerryshaw12" <notifications@github.com>:

**Comment by jerryshaw12** [comment]
https://mega.nz/#!tVIUCBKQ!DByjVBuCcyaVhQtQwReqMvUNYAbx7o-v0Z_E3mXuz50

**Comment by Grarak** [comment]
Thanks will be fixed in the next beta

**Comment by jerryshaw12** [comment]
The issue is still available in MIUI rom https://mega.nz/#!MYIQgRjJ!2q1DeMTCF6yff3HcVYFIe7Fjx5zgAlukdpgRiOGLAvc

**Comment by Grarak** [comment]
can you get me /proc/cpuinfo?

**Comment by jerryshaw12** [comment]
Processor : AArch64 Processor rev 2 (aarch64) processor : 0 BogoMIPS :
26.00 processor : 1 BogoMIPS : 26.00 processor : 2 BogoMIPS : 26.00
Features : fp asimd aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp
edsp neon vfpv3 tlsi vfpv4 idiva idivt CPU implementer : 0x41 CPU
architecture: 8 CPU variant : 0x0 CPU part : 0xd03 CPU revision : 2
Hardware : MT6795M
