### ISSUE TITLE
Need delay settings

### ISSUE THREAD

**Issue by shrichanakya** [Grarak/KernelAdiutor#41]
Some kernels apply their settings after sometime. The should allow for delay so that settings from kernel are overrides by the app. Eg Uber kernel uses 30 seconds time before settings are applied. Due to this my settings from this app never gets applied.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/47d6ffe37580a6eeee068119c27b4e5f1d8f2b62
