### ISSUE TITLE
Apply on boot disabled, not removing cached/saved settings?

### ISSUE THREAD

**Issue by Waester** [Grarak/KernelAdiutor#417]
Hey,

I don't know if it is a feature or bug. But when I disable "Apply on boot" and restarts the phone to get the default settings from the kernel and then apply new settings from scratch, the old settings from previous "Apply on boot" is used on top of the new/default settings on the next reboot when "Apply on boot" is used again.

This can be recreated by:

(0. Reset KA and reboot phone to fresh state.)
1. Change 2 settings of your choice in same category (CPU) and enable apply on boot.
2. Reboot (Let settings apply after reboot)
3. Disable apply on boot
4. Reboot (To get kernel default)
5. Change only one of the previous two settings (from step 1.) and enable apply on boot
6. Reboot (Let settings apply after reboot)

Result: Both the settings from step 1. is applied even though we only changed one of them (step 5.) and let the other one be kernel default.

Expected result: Only one of the settings is applied the other one should be kernel default.

**Comment by Grarak** [comment]
Disabling apply on boot does not delete any settings.
