### ISSUE TITLE
Request: NEW msmthermal sultanxda simple

### ISSUE THREAD

**Issue by affanse** [Grarak/KernelAdiutor#418]
Add support for 8 thermal throttle zones.

Instead of being limited to 3 thermal throttle zones (low, mid, high), use an array and make the amount of usable thermal zones easily expandable. 

The number of available thermal zones can be easily expanded in the future, though 8 should be sufficient for now. Negative temperatures can also be configured now. Use of all 8 thermal zones is not necessary; instead, only configure the amount needed, and the driver will not look at the unused zones. 

Usage: echo "throttle_freq trip_temp reset_temp" > /sys/kernel/msm_thermal/zoneX 

Ex: 
echo "1728000 39 38" > /sys/kernel/msm_thermal/zone0 echo "1574400 42 40" > /sys/kernel/msm_thermal/zone1

echo "960000 62 60" > /sys/kernel/msm_thermal/zone6 

Note that in this example, the 8th thermal zone (zone7) is not used. 
Frequencies are in kilohertz and temperatures are in degrees Celsius.

https://github.com/sultanxda/android_kernel_oneplus_msm8974/commit/a603b664261db9565658842a1f02436b2b489c87

**Comment by Grarak** [comment]
There is no way to detect if a device supports this, neither a there is a way to detect the correct sys path. There are multiple path for /sys/kernel/msm_thermal/zone*
