### ISSUE TITLE
A profile set for those newbie.

### ISSUE THREAD

**Issue by Schucz** [Grarak/KernelAdiutor#421]
I figured out that nowadays the audience rooted their device is all out to get an particular app require root access. But have no ideal what the apps does and how it benefit them yet able to go do so tweak till ending their bricking their device. 

What I recommend  is to warn the users that this app is only suitable for advanced user. 

Or provide a profile created for users based on their kernel and the system and create a recommended profile to select .

**Comment by Grarak** [comment]
If you rooted your device you should be aware of bricking risk. Ain't nobody got time to do a profile for each device and kernel.
