### ISSUE TITLE
unable to work on KSM page

### ISSUE THREAD

**Issue by madhacker3kxl** [Grarak/KernelAdiutor#422]
The KSM page always resets to top of the page when it automatically updates the data. I am unable to change any settings as it just goes back to top of the page where it brings up the "at boot" toggle.

**Comment by Grarak** [comment]
yeah forgot about his, thanks to the reminder

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/abf2fad5f5550e569ca493122fecb0347b3bac32
