### ISSUE TITLE
KCAL - Advanced color control color profiles

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#43]
Can you add color profile loading for the new KCAL driver?

The text files format is 2 lines (first is colors, second is controls):
kcal
kcal_sat kcal_val kcal_cont kcal_hue

You can add a default button to set the default profile:
256 256 256
30 127 127 0

**Comment by Grarak** [comment]
They are already supported
Am 03.03.2015 13:08 schrieb "engstk" <notifications@github.com>:

**Comment by engstk** [comment]
I don't see buttons to load the color profiles, it's in a new beta?

**Comment by Grarak** [comment]
You can open profile tab and save your current screen settings.

**Comment by engstk** [comment]
Yes, but these are color profiles that work multikernel and multidevice.
Not a Adiutor profile, but a color profile itself users can share with each other and load on favorite apps.

**Comment by DespairFactor** [comment]
I see Franco has profiles, are these the same thing? They ship with the kernel right?

**Comment by Grarak** [comment]
No, profiles are "hardcoded" in the app. I'm still not sure about this.

**Comment by engstk** [comment]
Yes seems like franco uses them hardcoded, which is pointless.
I think next versions of his app will have import from file, in that format I pointed out.

Let's keep this in stand by until then.

**Comment by Grarak** [comment]
The problem is that no other app uses that format. So I don't see the point to add this.
