### ISSUE TITLE
Problem on zram max_comp_streams

### ISSUE THREAD

**Issue by affanse** [Grarak/KernelAdiutor#431]
Changing zram size make max_comp_streams value changing to 1.

Before:
cat /sys/block/zram0/max_comp_streams
4

After changing the zram value in kernel adiutor

cat /sys/block/zram0/max_comp_streams
1

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/b307644e21c6649c15bd835660ded1e1abc75901

**Comment by affanse** [comment]
Hi @grarak, seems this bug is not fixed yet. It still reset to 1. Maybe you must set disksize to zero first before setting up new disksize and maxcompstreams values. Please kindly see my shell script below as an example. I used to change zram size and disksize with this code:

#!/bin/sh

zramsize=$((400 * 1024 * 1024))
streams=4

cat /sys/block/zram0/disksize
cat /sys/block/zram0/max_comp_streams

swapoff /dev/block/zram0

if [ $? -eq 0 ]; then
   echo 1 > /sys/block/zram0/reset
   echo 0 > /sys/block/zram0/disksize
   echo $streams > /sys/block/zram0/max_comp_streams
   echo $zramsize > /sys/block/zram0/disksize
   mkswap /dev/block/zram0
   swapon /dev/block/zram0
fi

cat /sys/block/zram0/disksize
cat /sys/block/zram0/max_comp_streams

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/07dd1a0685c0c08db96c206471e4f60b29394263

**Comment by affanse** [comment]
Could you please add an inputbox to change the max_comp_streams value.

**Comment by Grarak** [comment]
min, max and description

**Comment by affanse** [comment]
Ups sorry my bad.. Future zram will use max_comp_streams exactly as cpu number. 1 cpu = 1 stream.
So there is no need to add it. Although right now it can be set to whatever number we want and the kernel will decide whether to use it or not.
