### ISSUE TITLE
problem in CPU Governor Tunables

### ISSUE THREAD

**Issue by affanse** [Grarak/KernelAdiutor#432]
For example if changing a value to a number that exist in available frequency list then it will turn into a cpu frequency list.

Say that I have 300000 in available freqiency list, then I change "timer slack" to 300000, then it will turn into a frequecy list.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/6460713634cd889b77bf89d43ee3b98e0298243b
