### ISSUE TITLE
custom control seekbar issue

### ISSUE THREAD

**Issue by wazeeahmed** [Grarak/KernelAdiutor#443]
I created seekbars and switches for enabling thundercharge and gpu hotplug threshold . The switches work fine . But the seekbar doesn't . How I set the seekbar configs are like this :

Min : 0 ; Max : 100 
progress : 
echo 75 
applying : 
progress=$1
echo $progress > /sys/kernel/thunderplug/gpu_hotplug_enabled
Thundercharge  :

Min : 0; Max : 1000
progress : 
echo 1000
applying :
progress=$1
echo $progress > /sys/kernel/thundercharge_control/custom_ac_current

same procedure just custom_usb_current this time instead of custom ac current for usb charger . I have added the logcat for help .
[logcat.txt](https://github.com/Grarak/KernelAdiutor/files/428463/logcat.txt)

**Comment by Grarak** [comment]
cat /sys/kernel/thunderplug/gpu_hotplug_enabled instead of echo 75

**Comment by wazeeahmed** [comment]
So Is that something I have to fix or you're releasing an update with the fix ? Your app is the main controller of resurrection remix and know ; I like your controller app so much . Just that android one devices didn't have support . But there's this guys swapnil solanki who made zeus control based on your app has complete sysfs paths included there . I wish I could find out all sysfs paths ( most of them are included in your controller ; except gpu hotplug , hotplug threshold , core control and thundercharge control , thundersonic engine , thunderquake engine is missing ; which varun chitre had included as his own commit . Should I open up a pull request or send'em up to ya via email ? Though I couldn't find the gpu core control settings under /sys yet .
