### ISSUE TITLE
Implement Devil Kernel Manager functionality

### ISSUE THREAD

**Issue by KOLANICH** [Grarak/KernelAdiutor#46]

**Comment by Grarak** [comment]
Not specific enough

**Comment by KOLANICH** [comment]
To be more specific, the most needed features from dkm for me are power saving mode (/sys/module/cpuidle_exynos4/parameters/enable_mask) and keys highlight (/sys/class/sec/sec_touchkey/force_disable).

**Comment by Grarak** [comment]
I don't know what they do. I don't know how to read out the value. I don't know how to change thpse values.
