### ISSUE TITLE
Does Kernel Adiutor works with Toybox?

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Grarak/KernelAdiutor#465]
As Wikipedia, Toybox is included with Android 6.0 "Marshmallow" and all later Android versions, so if Kernel Adiutor works well with both BusyBox and Toybox, it would be nice for Android 6.0+.

**Comment by Grarak** [comment]
Dude it's supported since a year already.

**Comment by KrasnayaPloshchad** [comment]
Thanks.
