### ISSUE TITLE
Bug: user can bring down the first core

### ISSUE THREAD

**Issue by KOLANICH** [Grarak/KernelAdiutor#48]
Which will cause either hang or reboot

**Comment by Grarak** [comment]
No that's not possible

**Comment by KOLANICH** [comment]
It is posdible. At least on Devil kernel on n7100

**Comment by DespairFactor** [comment]
I have yet to see a device that this happens on, perhaps you should set parameters in your kernel that stops this from happening.

**Comment by Grarak** [comment]
If this is possible then the kernel is fucked up.
