### ISSUE TITLE
KSM slider is not user-friendly when using remote control for TV

### ISSUE THREAD

**Issue by yfdyh000** [Grarak/KernelAdiutor#480]
The other controls of the app can be manipulated when using the remote control, but if I want to efficiently adjust the KSM delay slider, I have to use an external mouse, because it's step are 1ms throughout, there is not a larger (e.g. 10ms) or variable step (accelerate with press time) or optional input box.

The issue same applies to the ZRAM slider, but it's 10MB step, not agile but acceptable.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/6eaea518222b08d24faa9ca07aba1bebf7f3de8f
