### ISSUE TITLE
apq8084 GPU temp?

### ISSUE THREAD

**Issue by github-cygwin** [Grarak/KernelAdiutor#482]
Hi,

I'm working on porting CM to Samsung Galaxy S5+ (kccat6) and I noticed that the GPU temp is missing in KA's "General" section.  Commit 5c0b335 added CPU temp readout for the apq8084 but GPU temp is missing.

Apq8084 provides thermal_zone5 for the CPU just as the predecessor msm8974.  The kccat6 kernel uses the same msm8974-tsens module as the msm8974 itself.  So, is it invalid to assume that GPU temp is thermal_zone9, just as on msm8974?  If yes, what do I have to do to find out the right themal_zone for the GPU temp?

Thanks,
Corinna

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/0b3971045832929e8f57956cdad4fce0b171c5b7
