### ISSUE TITLE
SELinux Adjustment

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#49]
Would be nice to see this app have an option to set SE to Permissive or Enforcing.

To set kernel to Permissive through terminal: setenforce 0 

Some mods like V4A require the kernel's security to be set to Permissive. There's already a Google Play app that adjusts SE and applies it on boot, but I would prefer my system tools to be in one app.

**Comment by engstk** [comment]
Don't forget the most important, the path:

/sys/fs/selinux/enforce (1 or 0)

**Comment by Grarak** [comment]
In this case I don't need the path.
busybox does that with setenforce

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/22ac68f732451a89d816a8d10239d220cd41a24a
