### ISSUE TITLE
Vibration Sensitivity

### ISSUE THREAD

**Issue by ddhalbrook** [Grarak/KernelAdiutor#5]

**Comment by Grarak** [comment]
Paths please.

**Comment by youlunzhai12** [comment]
sys/devices/virtual/timed_output/vibrator

**Comment by Grarak** [comment]
There are tons of different paths. Some even got the same one, but with different min and max values. I doubt I will add this.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/70ee7f76d1df02775ceae376933a6c71770df761

added
