### ISSUE TITLE
Wakelock blocker fo MSM

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#505]
This are a few wakelock block enable/disable interface, available in several MSM devices including OP3/3T

SYSFS (Y:enabled | N: disabled)
/sys/module/wakeup/parameters/enable_ipa_ws
/sys/module/wakeup/parameters/enable_netlink_ws
/sys/module/wakeup/parameters/enable_qcom_rx_wakelock_ws
/sys/module/wakeup/parameters/enable_timerfd_ws
/sys/module/wakeup/parameters/enable_wlan_extscan_wl_ws
/sys/module/wakeup/parameters/enable_wlan_ws

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/83cd672f47c644153c7ba6dd77c0fa06bd00f33c
