### ISSUE TITLE
CPU voltage Global Offset issues

### ISSUE THREAD

**Issue by jj999** [Grarak/KernelAdiutor#506]
There are 3 issues related to CPU voltage settings (in recent version 0.9.6.9):
1. If I set "Global Offset" for CPU voltage, no matter what value I select (-5, -10, -15...) the resulting "on boot" entry is always -5. (Expected behaviour - on-boot should match value set)
2. If I try to decrease CPU voltage, voltage of all frequencies is decreased, but if I try to increase it, all other frequencies stay the same. (Expected behaviour - increasing should be consistent with decreasing)
3. If Global Offset is already set on boot and you reboot the phone, the displayed value of CPU voltage is not clear - for example "Global Offset" shows 0 value again, despite it was decrease on boot. (Expected behaviour would be to display persistent voltage Global Offset value and not to start relatively from 0 after each reboot)
Thank you!

**Comment by Grarak** [comment]
Not possible when user uses another kernel app. Also devices have different voltage steps.

**Comment by jj999** [comment]
Hello Garak, you answer is for point 3 - I understand and accept that. But points 1 and 2 refer to bug in GUI and these are not resolved. Thnx.

**Comment by Grarak** [comment]
My answer covers all points. It's not a bug. It's intended.
