### ISSUE TITLE
Add AiO HotPlug (complete sysFS entries and Descriptions are provided)

### ISSUE THREAD

**Issue by Shoaib0597** [Grarak/KernelAdiutor#515]
**Hi @Grarak,**

I request you to add **AiO HotPlug**, an All in One HotPlug for Traditional Quad-Core and Hexa/Octa-Core big.LITTLE SoCs. **I have developed this HotPlug myself**.

This HotPlug offers **a total of 4 sysFS entries**. They are **(order-wise)**---

**1. Enable/Disable Toggle---**
**sysFS Path---**
/sys/kernel/AiO_HotPlug/toggle
**Range---**
1 or 0

**2. A Traditional "Number of Online Cores" SeekBar---**
**sysFS Path---**
/sys/kernel/AiO_HotPlug/cores
**Range---**
1 to 4

**3. A "big Cluster" SeekBar---**
**sysFS Path---**
/sys/kernel/AiO_HotPlug/big_cores
**Range---**
0 to 2 (on Hexa-Core big.LITTLE SoCs)
0 to 4 (on Octa-Core big.LITTLE SoCs)
**Note:**
At value 0, the entire Cluster will be switched off.

**4. A "LITTLE Cluster" SeekBar---**
**sysFS Path---**
/sys/kernel/AiO_HotPlug/LITTLE_cores
**Range---**
0 to 4
**Note:**
At value 0, the entire Cluster will be switched off.

**Misc. Notes--**
1. The HotPlug will expose only 1 and 2 sysFS entries if it is running on a Traditional Quad-Core SoC.
2. The HotPlug will expose only 1, 3 and 4 sysFS entries if it is running on a Hexa/Octa-Core big.LITTLE  SoC.

**Optional Requests (I have already created perfectly working Custom Controls (a great feature, thanks!) for this HotPlug)---**
**1. Titles and Descriptions---**
   **a. Enable/Disable Toggle---**
   **Main Title**-----AiO HotPlug
   **Description**---An All in One HotPlug, developed by Shoaib Anwar a.k.a. Shoaib0597, for all main types of SoCs. 
   
   **b. "Number of Online Cores" SeekBar**
   **Main Title**-----Number of Online Cores
   **Description**---No Description (Leave Blank)

   **c. "big Cluster" SeekBar---**
   **Main Title**-----big Cluster
   **Description**---Set the Number of Online Cores. At value 0, the entire Cluster will be switched off (only if atleast 1 LITTLE Core is active and HotPlug Boost Toggle (available in CPU TAB) is Enabled).
   **Note:** At value of 0 of this SeekBar, instead of showing "0", show "Offline".

   **d. "LITTLE Cluster" SeekBar---**
   **Main Title**-----LITTLE Cluster
   **Description**---Set the Number of Online Cores. At value 0, the entire Cluster will be switched off (only if atleast 1 big Core is active).
   **Note:** At value of 0 of this SeekBar, instead of showing "0", show "Offline".

**2. Please, if possible, try to copy/paste these descriptions exactly.** :)

**Thanks! I hope this gets merged soon. :)**

**Comment by DidntRead** [comment]
Is this okay?
https://www.dropbox.com/s/ogqbmq1t5m2j0dx/KernelAdiutor%28AiO%29.apk?dl=0

**Comment by Shoaib0597** [comment]
@DidntRead,

No, there was only Core Control in CPU HotPlugs TAB. There was no AiO anywhere. :|

**Comment by DidntRead** [comment]
https://www.dropbox.com/s/f7ozoiho592iwmf/KernelAdiutor%28AiO%29.apk?dl=0

**Comment by Shoaib0597** [comment]
@DidntRead,

I want this in Grarak's Official KA. Your BUILDs are of no use to me because all my Kernel users use Grarak's KA only. :)

**Comment by Grarak** [comment]
"Number of Online Cores"
What does this do exactly?
Min. cpu used or max cpu used?

**Comment by AyushR1** [comment]
Max Cpus used for an quad core soc.

**Comment by Shoaib0597** [comment]
@Grarak 
It controls the Max. No. of Cores Online.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/54d8fb9c1fdda6dc2c71d80b69168ac496a8cc12

**Comment by thtkidsvm** [comment]
Hi, i've added AiO hotplug to a kernel (lambda kernel lg g2) for my phone which is traditional quad core snapdragon 800. Is this hotplug driver suppose to online all cpus set by number of online cores constantly? It seems none of the cores go offline once I enable the hotplug driver.
