### ISSUE TITLE
Emulate init.d 

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#52]
Have an option to emulate init.d for ROMs that don't support it.

Path: /system/etc/init.d

Most ROMs don't support this, but androguide.fr has an app that emulates init.d for all ROMs with root/busybox. If you need more info, I'll try my best to provide some details, though truthfully my knowledge on this is rather lacking.
 
Here's the link to his project if you need some sort of reference: https://github.com/Androguide/Universal-init.d/tree/master/src/com/androguide/universal/init/d

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/d950530871c02b5f171cb346766db020ae0ff146
