### ISSUE TITLE
Add Photo References in the Screen tab

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#53]
It would be nice to have some sort of photo reference (like a picture of a parrot or an apple) when changing colors or calibrating the displace.

For paths, I guess you can have a look at these examples in the links ;-)

http://webneel.com/daily/sites/default/files/images/daily/04-2013/15-mult-color-photography.preview.jpg
http://webneel.com/daily/sites/default/files/images/daily/04-2013/2-colorful-photography.jpg
http://webneel.com/daily/sites/default/files/images/daily/04-2013/7-colorful-photography.jpg
http://webneel.com/wallpaper/sites/default/files/images/04-2013/25-vibrant-color-photography.jpg
http://webneel.com/wallpaper/sites/default/files/images/04-2013/23-colorful-photography.jpg

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/cb342bd84119c8c31e855ecd5fb411ef1334b3f5
