### ISSUE TITLE
Revert to Default

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#55]
Have the users be able to revert all settings (or a specific setting) to a default value.

**Comment by Grarak** [comment]
I don't see any reason to add this. The user can simply do a reboot to go back to the default.

**Comment by kentallenduke** [comment]
If they changed a bunch of settings, I understand a reboot would do. But if I forgot the value of one setting, a reboot will take too much time.

**Comment by theowner997** [comment]
I agree with this suggestion, sometimes I only mess with one option, and I forget what's the default value. An undo or reset button would be perfect I believe.

**Comment by Grarak** [comment]
This is not possible. It's not possible to get default values.
