### ISSUE TITLE
Add delay online for CPUHotplug

### ISSUE THREAD

**Issue by GreyLeshy** [Grarak/KernelAdiutor#551]
Hi, please add delay online for CPUHotplug.

[Add-Online-Delay-for-CPUHotplug.patch.txt](https://github.com/Grarak/KernelAdiutor/files/1314562/Add-Online-Delay-for-CPUHotplug.patch.txt)

**Comment by dani020110** [comment]
@GreyLeshy is it okay if I pull request for you? of course keeping the authorship
https://github.com/dani020110/KernelAdiutor/commit/a12eb54949663f40cee7d9349434f3c6640f1f42

**Comment by GreyLeshy** [comment]
@dani020110 
Yes, that's fine. Thank you!

**Comment by GreyLeshy** [comment]
@dani020110 
Oh, I just saw a few errors in the patch.

**Comment by GreyLeshy** [comment]
@dani020110 Now everything accurately.
[Add-Online-Delay-for-CPUHotplug.patch.txt](https://github.com/Grarak/KernelAdiutor/files/1320686/Add-Online-Delay-for-CPUHotplug.patch.txt)

To check the patch I can not, because when you compile:
```
$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.45 secs
```

**Comment by dani020110** [comment]
@GreyLeshy Is this okay?
https://github.com/dani020110/KernelAdiutor/commit/61cff37bdfad287a7b9a9f761d4be65affad20f1
By the way it compiles fine but I could not test it because core_ctl doesn't compile on my kernel

**Comment by GreyLeshy** [comment]
@dani020110 
Yes OK. Thank you!
