### ISSUE TITLE
Alucard hotplug suport

### ISSUE THREAD

**Issue by borz93** [Grarak/KernelAdiutor#56]
Please, add Alucard Hotplug(from XDA Member alucard_24) suport for this app. This hotplug is very batery friendly. 
Kernel as AndroPlus for Xperia z2 and z3 support this, and alucar Kernel for galaxy devices, for example.
Thanks alot.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/1f9fe98850e444132e5373ca173047c008193894

**Comment by borz93** [comment]
Thanks you very much for Alucard support in your app Dev!
