### ISSUE TITLE
cannot delete or add init.d scripts

### ISSUE THREAD

**Issue by crok** [Grarak/KernelAdiutor#567]
Dear Dev,

can you please let me know where are the init.d scripts are stored created in KA?

I created one but I want to delete it - it disappears but when I go back to init.d settings it is still there and it's content as well. I cannot even edit it, after saving and going back to editing the file's having the same content as before. I am really stuck now. I tried to delete the app data, reinstall it, many time - no success, even the new installation has the file.. and cannot delete it..

**Comment by abualeisan** [comment]
System/etc/init.d

**Comment by crok** [comment]
It was in /su but it was not able to delete it because that partition was mounted read-only.
