### ISSUE TITLE
Touch Boost

### ISSUE THREAD

**Issue by Fabi9228** [Grarak/KernelAdiutor#58]
it's indispensable for hellscore on my nexus 5

Hells kernel n5: http://forum.xda-developers.com/google-nexus-5/general/support-hells-core-kernel-nexus-5-t2873942

Example:
https://dl.pushbulletusercontent.com/u9QPB041KKOIaQWo4tbxjWS5eqeTPg0L/Screenshot_2015-03-12-15-54-42.png
or
https://dl.pushbulletusercontent.com/XhYpexGNY5jJUSojkNmsZGwgFp5PMQjr/Screenshot_2015-03-12-15-55-58.png

Thanks for this amazing kernel manager :)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/4ae0de5fd6858991259e8ebdcfe30747e089a07a
