### ISSUE TITLE
Wrong position of handle

### ISSUE THREAD

**Issue by ChristophHeilmann** [Grarak/KernelAdiutor#584]
In the build.prop editor the text selection handle is on the wrong position (top left corner). I own a Xperia Z4 Tablet with Marshmallow 6.01 and use that tablet only in landscape view.

Regards,
Christoph

**Comment by garga3838** [comment]
{

  "version": 1,

  "control": {

    "apply": "#!/system/bin/sh\n\nsetenforce $1",

    "enable": "#!/system/bin/sh\n\nif [ `getenforce` == \"Enforcing\" ]; then\n echo 1\nelse\n echo 0\nfi",

    "title": "Selinux",

    "description": "Security-Enhanced Linux is a Linux kernel security module that provides a mechanism for supporting access control security policies.",

    "id": "switch"

  }

}

**Comment by garga3838** [comment]
https://github.com/Grarak/KernelAdiutor/issues/584#issuecomment-428827227

**Comment by garga3838** [comment]
https://github.com/Grarak/KernelAdiutor/issues/584#issuecomment-428827227

**Comment by ChristophHeilmann** [comment]
It was the immersive mode which caused the error. I disabled it and all is fine now.
