### ISSUE TITLE
CFS Scheduler Policy (Multicore Power Saving)

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#60]
The possible values are in a string in:
/sys/devices/system/cpu/sched_balance_policy/available_sched_balance_policy (normally performance and powersaving)

The set value is a string in:
/sys/devices/system/cpu/sched_balance_policy/current_sched_balance_policy

Check info: https://github.com/engstk/shamu-5.0/blob/f48e3201760cb8464b435a5cf916e97cd3a188d2/Documentation/ABI/testing/sysfs-devices-system-cpu

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/b7bf398529c26ccc4478f65dc55bd6a945d36268

**Comment by engstk** [comment]
Thanks mate
