### ISSUE TITLE
Tabella Frequenze in LIVE

### ISSUE THREAD

**Issue by Piccions97** [Grarak/KernelAdiutor#62]
Implementare una funzione per l'aggiornamento automatico della tabella delle frequenze per favore :)

**Comment by Grarak** [comment]
Scusa ma non parlo l'italiano
Am 16.03.2015 20:56 schrieb "Piccions97" <notifications@github.com>:

**Comment by Piccions97** [comment]
In the frequency table, please add a function that let the live updating... It's very boring click everytime   the button "refresh"

**Comment by Grarak** [comment]
It takes alot time to calculate those states. It would make your phone lag
if I would add that
Am 16.03.2015 21:03 schrieb "Piccions97" <notifications@github.com>:

**Comment by Piccions97** [comment]
you' re right... Thanks for the support. You can close this request now :) byee
