### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by GasLoop** [Grarak/KernelAdiutor#65]
Please update the APK on the F-Droid Store, thanks.

**Comment by Grarak** [comment]
I'm not responsible for F droid
Am 19.03.2015 01:54 schrieb "GasLoop" <notifications@github.com>:

**Comment by GasLoop** [comment]
Oh, any clue who is? I'd do it too, if I knew how to do it.

**Comment by Grarak** [comment]
Nope
They just pull my code and build it themselves
Am 19.03.2015 10:17 schrieb "GasLoop" <notifications@github.com>:
