### ISSUE TITLE
Simple reboot commands / flash zip

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#67]
I think simple reboot  /flash zip commands could be useful.
you can created a new item on flyout menu called Reboot / Flash with individual cards in it (or a selector for reboot and flash cards):
- Reboot
- Reboot to recovery
- Reboot to fastboot

 and add a 4th to choose zip  (or group of zips) to flash, with a file picker.
Can add a checkboxes/switch to clean cache after zip flash
+info on openrecovery (used by TWRP) on: http://wiki.rootzwiki.com/OpenRecoveryScript

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/edfba7e47ab53fed2d243f1e22337508cd9298bd

**Comment by engstk** [comment]
Very nice!

Ca'nt wait to test :)
