### ISSUE TITLE
Sunlight Enhancement mode

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#68]
Some panels support hbm (high brightness mode), here's the tunable:

/sys/devices/virtual/graphics/fb0/hbm (1 on or 0 off)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/32d7d775dce0db6b3f621b56c1e8b14a9b734f39

**Comment by engstk** [comment]
Thanks mate.
