### ISSUE TITLE
DT2W Feature

### ISSUE THREAD

**Issue by till22** [Grarak/KernelAdiutor#7]
Dear reader,

First of all: very very nice design!

A very nice and handy feature for the Nexus 5 dt2w feature would be to have a timeout option for it. The dt2w feature consumes more than 1% per hour on our device, so it is quite unusable right now. It would be awesome if you could implement it! You can always contact me under till22 on XDA.

Cheers,
Till

**Comment by till22** [comment]
By timeout, I mean that the dt2w feature gets auti disabled after X minutes of sleep/screen off.

**Comment by Grarak** [comment]
That feature depends on your kernel.
I will add this later

**Comment by till22** [comment]
It is supported, I have to edit the .conf file now. Thanks!
