### ISSUE TITLE
Suport Power suspend modes and intellithermal by faux123

### ISSUE THREAD

**Issue by attack11** [Grarak/KernelAdiutor#70]
Suport Power suspend modes and intellithermal by faux123

Thats are the only missing features i found in  your  awesome app, what info you need to add them? In  case you want to, thanks !

**Comment by borz93** [comment]
Hi Grarak,this may be helpful:

# Enable and configure intelli thermal
echo "Y" > /sys/module/msm_thermal_v2/parameters/enabled
echo "1" > /sys/module/msm_thermal_v2/core_control/enabled
echo "65" > /sys/module/msm_thermal_v2/parameters/core_limit_temp_degC
echo "70" > /sys/module/msm_thermal_v2/parameters/limit_temp_degC
echo "250" > /sys/module/msm_thermal_v2/parameters/poll_ms
echo "0" > /sys/module/msm_thermal_v2/vdd_restriction/enabled
echo "12" > /sys/module/msm_thermal_v2/parameters/core_control_mask
echo "15" > /sys/module/msm_thermal_v2/parameters/freq_control_mask

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/105773b812cd86ca01d45b221e133923d86ccd0a
