### ISSUE TITLE
DashClock Extension 

### ISSUE THREAD

**Issue by Micky007** [Grarak/KernelAdiutor#71]
Well,for first in must say :EXCELLENT work! Your app is the best graphical made  and more general feature-rich ! 
As the title says I was thinking about how great could be a DashClock extension, I hope this  could be a great idea for you to make your app better  and I hope absolutely I'm not asking too much. I count on your willingness and I wish you  to  a  good development!

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/9259c9095ae7bce7c2bc57709d78e5924782b48d

**Comment by Micky007** [comment]
So Many Thanks!When I've seen this new feature added,I felt so good,you mare my wish realize.GOOD DEVELOPMENT!
