### ISSUE TITLE
S2W, DT2W does not work with Boeffla kernel

### ISSUE THREAD

**Issue by gunine** [Grarak/KernelAdiutor#72]
First of all, really appropriate all the effort for making such a wonderful application.
I am a Galaxy S5 user, and currently using boeffla kernel. 
The source can be found in https://github.com/andip71/boeffla-kernel-samsung-s5/ .
This kernel supports "Screen wake and sleep functions", such as S2W, DT2W and so on. However with Kernel Adiutor, the option does not appear on the screen.
I hope the authors can consider adding this feature for Galaxy S5 user into the Kernel Adiutor application.
The corresponding commit which realizes the Screen Wake and Sleep Functions (in kernel level) can be found in following URL.
https://github.com/andip71/boeffla-kernel-samsung-s5/commit/6e8d70c7b61c3dc7f21fbd7c98f80f382b3abd58

**Comment by Grarak** [comment]
I need paths and their values

**Comment by gunine** [comment]
The full path of configurable variables is /sys/devices/f9924000.i2c/i2c-2/2-0020/input/input2/.
There are five configurable variables which are screen_wake_options, screen_wake_options_prox_max, screen_wake_options_debug, screen_wake_options_when_off and screen_sleep_options. But I think only two variables are need to be configured.

To wake the device only need to assign value to screen_wake_options variable.
There are five values can be assignable to screen_wake_options, which are 
0 = disabled; 1 = s2w; 2 = s2w only while charging; 3 = dtap2wake; 4 = dtap2wake only while charging; 5 = both; 6 = both while charging.

There are two values can be assignable to screen_sleep_options, which are 
0 = disabled; 1 = dtap2sleep

For the detail please refer to the file https://raw.githubusercontent.com/andip71/boeffla-kernel-samsung-s5/6e8d70c7b61c3dc7f21fbd7c98f80f382b3abd58/drivers/input/kt_wake_funcs.c (line 19 - 23).

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/de10927d4e6e9d4d1d363fb859be69463cb4a390
