### ISSUE TITLE
Support for gpu frequency and governor control for adreno 405 gpu (SD615) and more material design needed..

### ISSUE THREAD

**Issue by falcon97** [Grarak/KernelAdiutor#73]
GPU frequency and governor is not adjustable with this appfor the adreno 405 gpu's.....My kernel supports that feature as am able to adjust it with other apps....So I request you to see to this issue....Also make the material design more cool...make use of the brand new sdk..Other than that app is cool...

**Comment by Grarak** [comment]
Paths and values please.
And what do you mean with "more cool"? This app already uses the latest SDK version.

**Comment by falcon97** [comment]
Path for the gpu frequencies:

/sys/devices/soc.0/1c00000.qcom,kgsl-3d0/devfreq
Under this folder the files to be edited are:
For min freq : min_freq
For max freq : max_freq
For governors : governor

And finally the available frequencies are : 
550000000 (550mhz)
400000000 (400mhz)
220000000 (220mhz)

The available governors are : 
bw_hwmon
msm-adreno-tz
cpufreq
userspace
powersave
performance
simple_ondemand

**Comment by falcon97** [comment]
And about the material design...actually i was about to tell that for each tab u can add a different coloured action bar so that it would be nyc and eye catchy...and abt that sdk version sorry for being lame...and another thing is that the set on boot switch button and the action bar is of same colour...so if u could change the colour of the switch button it would be nyc....other than that.. The app is coolest of the cool for the free price at which u are giving...thank u...

**Comment by Grarak** [comment]
The paths are not enough. There are files which contain the available frequencies and governors. Also current freq is missing.

**Comment by falcon97** [comment]
Ok here is the complete path without any symlinks...

For the max freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/max_freq

For the min freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/min_freq

For the current freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/cur_freq

For the available freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/available_frequencies

For the target freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/target_freq

For the current governor :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/governor

For the available governor :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/available_governors

If anyother path needed i will surely provide... :)

**Comment by Grarak** [comment]
Could you also cat them?

**Comment by falcon97** [comment]
Ok...its n8 here...i will provide u the logcat by tmrw mrng... :)

**Comment by Grarak** [comment]
I don't want a logcat. With cat I mean read the files and provide me the content.

**Comment by falcon97** [comment]
Okay....i will edit the previous post and u can see the contents in it...

**Comment by falcon97** [comment]
I have updated the comment with the respective contents of the files...

**Comment by falcon97** [comment]
For the max freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/max_freq

Contents : 
550000000

For the min freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/min_freq

Contents : 
220000000

For the current freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/cur_freq

Contents : 
400000000

For the available freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/available_frequencies

Contents : 
550000000 400000000 220000000

For the target freq :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/target_freq

Contents : 
400000000

For the current governor :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/governor

Contents : 
msm-adreno-tz

For the available governor :
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/available_governors

Contents : 
bw_hwmon msm-adreno-tz cpufreq userspace powersave performance simple_ondemand

**Comment by Grarak** [comment]
I don't think these are the correct paths.
Type in shell
find /sys -name "gpuclk"

and give me the output

**Comment by falcon97** [comment]
/sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl-3d0/gpuclk

**Comment by Grarak** [comment]
Thanks.
Now please list the files and their content of this path /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl-3d0

**Comment by falcon97** [comment]
/sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/gpuclk

Content : 400000000

/sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/gpu_available_frequencies

Content : 550000000 400000000 220000000

/sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk

Content : 550000000

**Comment by Grarak** [comment]
Does this folder exists /sys/devices/soc.0/1c00000.qcom,kgsl-3d0/kgsl-3d0/devfreq ?

**Comment by falcon97** [comment]
For the govrnors actually,i use devfreq support so the above said is the link for governors.

**Comment by falcon97** [comment]
Sorry for closing the issue...
And actually the link said by u is actually a mistake by me...i updated the comment...so that link doesnt exist...the link sent by me in the next comment is the original link...sorry for the inconvenience..

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/ad669bcc121b516eb165ef4b1dfae961a8cdc16d

**Comment by falcon97** [comment]
Sir everything works fyn...sorry for the inconvinience..but the governor link is actually 

/sys/devices/soc.0/1c00000.qcom,kgsl-3d0/devfreq/1c00000.qcom,kgsl-3d0/available_governors

And 

/sys/devices/soc.0/1c00000.qcom,kgsl-3d0/devfreq/1c00000.qcom,kgsl-3d0/governor

Other than that everything works gr8...frequemcy is adjustable... :)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/1ec92f3acf1e60275d28fb44feea39fede98cf73

**Comment by falcon97** [comment]
Works gr8...tqsm..
