### ISSUE TITLE
Per cpu core frequency control and governor control

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#74]
I request you to add feature to adjust the scalin max and min freq and governor per cpu wise and not as a whole block....It would be more cool... :)

**Comment by Grarak** [comment]
That's unnecessary. I don't see the point to add this.

**Comment by falcon97** [comment]
Mine is an octa core cpu... If u add that the i can adjust in a  way that the last 4 cores are power savin ones and the primary 4 are perfomance oriented ones..

**Comment by Grarak** [comment]
If a core is offline it's not possible to read its freq and also not possbile to write set one.

**Comment by falcon97** [comment]
Oh okay...i got it now...how about making the first 4 as one block and next 4 as another block?? Is it possible?? Coz mostly 6 of my cores will always be active and wont be offline..Anyway its upto you... Peace.. :)

**Comment by zwliew** [comment]
He is probably talking about the HMP processor in SD615. I think the first 4 cores use a shared policy with CPU0, while the last 4 cores use a shared policy with CPU4

**Comment by falcon97** [comment]
Exactly....The heterogeneous Multiprocessing...But in my case it is not two different cortex variants, But the same cortex variant (Cortex A53)...Which should have been clocked at different ranges accordin to Qualcomm...(The first 4 cores should have been clocked at 1.5 ghz...while the last at 1.0 ghz...while our stock is something diff..all clocked at 1.5 ghz standard...)So it would be nyc if you consider this issue...Maybe helpful to HMP devices...

**Comment by Grarak** [comment]
I don't have any devices with HMP.
Devices with QCOM SoC have 2 cortex-a53 with different max freq.
But exynos devices like note 3 or galaxy s5 have cortex-a15 with cortex-a7
note 4 exynos has cortex-a53 and cortex-a57
It's quite hard to add support for all of them without breaking anything else

**Comment by zwliew** [comment]
How about checking for the availability of a cpu7 folder, before checking whether cpu0 and cpu3 have the different cpuinfo.max_freq? This should check whether the current device has a HMP processor.

**Comment by falcon97** [comment]
So actually i wanna ask about this issue or feature again...This time it has more relevance..i dont want it as per cpu , but can u make it as two seperate clusters of cpu?? Am asking this because now the available max frequency for our first 4 cores is totally different from the last 4..

The first 4 has a available maximum frequency of 1497 mhz and the last 4 has a available maximum frequency of 998 mhz..Pls take this issue into consideration...Am just askin you to make two individual cpu clusters so that they can be controlled seperately...this is for the sake of octa core chipsets...

**Comment by falcon97** [comment]
For proof and reference purpose :
These are available frequencies of cluster 0 that is cpu 0-3
![screenshot_2015-04-08-08-40-11](https://cloud.githubusercontent.com/assets/10761957/7038277/b80fc80c-ddcc-11e4-91ed-3fd4b702d2cb.png)

These are the available frequencies of cluster 1 that is 4-7
![screenshot_2015-04-08-08-40-41](https://cloud.githubusercontent.com/assets/10761957/7038265/9a8aa054-ddcc-11e4-96bd-549b593d1108.png)

**Comment by Grarak** [comment]
I can't do anything with these informations

**Comment by falcon97** [comment]
Ok....can u just provide me a list of which path u need please..so that i may provide u with the exact infos... Or jus tell me which infos u want...i will gather them and provide them ASAP..

**Comment by Grarak** [comment]
I need all path + their values of both clusters
Am 11.04.2015 20:01 schrieb "Dhinesh Ravi" <notifications@github.com>:

**Comment by falcon97** [comment]
For the CPUs 0,1,2,3 the paths are : 

Scaling available freq : 
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies

Contents:
![screenshot_2015-04-11-23-59-21](https://cloud.githubusercontent.com/assets/10761957/7102738/e83596c8-e0a7-11e4-9d73-b41eef6352f3.png)



Scaling min freq : 
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

Contents:
![screenshot_2015-04-11-23-59-31](https://cloud.githubusercontent.com/assets/10761957/7102739/f3228460-e0a7-11e4-82fa-3f35cfdb499a.png)


Scaling max freq : 
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

Contents:
![screenshot_2015-04-11-23-59-39](https://cloud.githubusercontent.com/assets/10761957/7102741/fc72d7cc-e0a7-11e4-8d56-099719f112a3.png)


Scaling available governor : 
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors

Contents:
![screenshot_2015-04-11-23-59-49](https://cloud.githubusercontent.com/assets/10761957/7102745/08967536-e0a8-11e4-9482-06404f6a8343.png)


Scaling current governor : 
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

Contents:
![screenshot_2015-04-11-23-59-59](https://cloud.githubusercontent.com/assets/10761957/7102749/118a126a-e0a8-11e4-8460-09acc544591b.png)


In the above actually the cpu 1,2,3 frequencies and others are symlinked to cpu 0's frequencies,governors etc...


For the CPUs 4,5,6,7 the paths are : 

Scaling available freq : 
/sys/devices/system/cpu/cpu4/cpufreq/scaling_available_frequencies

Contents:
![screenshot_2015-04-12-00-00-42](https://cloud.githubusercontent.com/assets/10761957/7102751/1d7f10a2-e0a8-11e4-9f21-41760e01e81f.png)


Scaling min freq : 
/sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq

Contents:
![screenshot_2015-04-12-00-00-53](https://cloud.githubusercontent.com/assets/10761957/7102754/320c00f2-e0a8-11e4-8118-a188c9c18ffb.png)


Scaling max freq : 
/sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq

Contents:
![screenshot_2015-04-12-00-01-00](https://cloud.githubusercontent.com/assets/10761957/7102775/0b66a65e-e0a9-11e4-8bc0-961c94dbd50f.png)


Scaling available governor : 
/sys/devices/system/cpu/cpu4/cpufreq/scaling_available_governors

Contents:
![screenshot_2015-04-12-00-01-11](https://cloud.githubusercontent.com/assets/10761957/7102776/1141bdd4-e0a9-11e4-8b4f-6b4b9f995f65.png)


Scaling current governor : 
/sys/devices/system/cpu/cpu4/cpufreq/scaling_governor

Contents:
![screenshot_2015-04-12-00-01-20](https://cloud.githubusercontent.com/assets/10761957/7102777/195fd37a-e0a9-11e4-85da-dae140dce825.png)


In the above actually the cpu 5,6,7 frequencies and others are symlinked to cpu 4's frquencies,governors etc...

**Comment by falcon97** [comment]
Scaling current frequency for CPUs 0,1,2,3
/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

Content :    
![screenshot_2015-04-12-00-19-32](https://cloud.githubusercontent.com/assets/10761957/7102791/db5c398c-e0a9-11e4-99f5-2166724d5ddb.png)



Scaling current frequency for CPUs 0,1,2,3
/sys/devices/system/cpu/cpu4/cpufreq/scaling_cur_freq

Content :    
![screenshot_2015-04-12-00-19-11](https://cloud.githubusercontent.com/assets/10761957/7102795/0a0a6cea-e0aa-11e4-9851-32ddf8dea5ba.png)

**Comment by falcon97** [comment]
Are these info enough or u want some more?? Coz i didnt get any response over this issue for several days...Am not blaming you coz u also would have a personal lyf and jobs to carry out...Am jus making an soft enquiry thats it...

**Comment by Grarak** [comment]
I'm busy

**Comment by Cardinal97** [comment]
I made a initiative in this issue without breaking the other things...It supports all the HMPs of current Qualcomm SD chipsets...U may cherry-pick it and make some changes according to ur needs..thanks in advance..

939e7db4a6394e3186c3a109e950d5b65f3a4349
7790f8a13d0508506f81e6e4bed7501c418906f7

**Comment by Cardinal97** [comment]
I dint get a proper idea over the per cluster governor tunables...so I initially added it to the first cluster....and left the cluster 2 blank over the governor tunables side..

**Comment by Cardinal97** [comment]
I actually asked u about integrating the above thing...Can u?? If not possible will you give me permission to upload my build in my phone's forum...I will give proper credits for it....For sure...The above is only if u are not wishing to integrate the code...Please dont think am over doing...just a formal request and a small help from my side.. :)

**Comment by Grarak** [comment]
I am about to implement this, but I need a reliable way to detect which cores are big or LITTLE. And how many cores each cluster has. How many cores does Kernel Adiutor shows you?

**Comment by Cardinal97** [comment]
8

**Comment by Cardinal97** [comment]
Thw big and small cores always vary in each chipsets....its not a big problem actually because...The structre is like the first four cores are always quad...and the only ones which differ are those last ones..
Only thing is that when we initialize set_frequency command we have to target only those parent cores...like the cpu0 and cpu4...
But when we get_frequency we have to make use of all those individual cores....In my commit there is a stupidity i guess...i would have jus got frequencies of those parent cores and not the child cores...

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/d65939c6be627f30f0c4f83fe515ab4f49727850

I didn't use your commit, sorry for that, but I needed something that would work with all big.LITTLE devices. Tested on my S5 with exynos. Should work on QCOM too.

**Comment by Cardinal97** [comment]
Its ok i want that feature thats it :P either it would be urs or mine....This is a global app...So ur I respect ur every move... :)
