### ISSUE TITLE
Support for gesture wakeup for some devices

### ISSUE THREAD

**Issue by falcon97** [Grarak/KernelAdiutor#75]
My device supports some list of wakeup gestures lik draw "e " to wake up, "o" to wake up,slide up,down,left,right to wakeup etc...I request u to add option to control this feature... The only file to be edited for this feature is : /sys/class/touchscreen/touchscreen_dev/gesture_wakeup

The register values for the different gestures are as follows : 

    TW_SUPPORT_NONE_SLIDE_WAKEUP = 0x0,
    TW_SUPPORT_UP_SLIDE_WAKEUP = 0x1,
    TW_SUPPORT_DOWN_SLIDE_WAKEUP = 0x2,
    TW_SUPPORT_LEFT_SLIDE_WAKEUP = 0x4,
    TW_SUPPORT_RIGHT_SLIDE_WAKEUP = 0x8,
    TW_SUPPORT_E_SLIDE_WAKEUP = 0x10,
    TW_SUPPORT_O_SLIDE_WAKEUP = 0x20,
    TW_SUPPORT_W_SLIDE_WAKEUP = 0x40,
    TW_SUPPORT_C_SLIDE_WAKEUP = 0x80,
    TW_SUPPORT_M_SLIDE_WAKEUP = 0x100,
    TW_SUPPORT_DOUBLE_CLICK_WAKEUP = 0x200,

For more references u can checkout my touchscreen driver source file : 

https://github.com/falcon97/android_kernel_yu_msm8916/blob/cm-11.0/drivers/input/touchscreen/gt9xx_yl/gt9xx.c

Checkout the lines from 175 to 195... Thank you..

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/f0a60bbe67481f557f4be37b09ce018dcdfab266

**Comment by falcon97** [comment]
Sir the values are not getting set properly...it stays to the default system values... i.e the double tap gesture... 0x00000200

**Comment by Grarak** [comment]
Those are the values you provided to me. Correct them.

**Comment by falcon97** [comment]
Also i am not able to set multiple gestures at same tym..If u want u can also refer this app which is actually only for supporting the gesture control...

https://github.com/vishal-android-freak/Fusion_Control?files=1

**Comment by falcon97** [comment]
I think the above sources will be helpful for u to fetch the values and also to add multiple gestures..

**Comment by Grarak** [comment]
Well it's not my task to do a proper research. I will remove this until you give me a detailed description of everything

**Comment by falcon97** [comment]
Ok sorry...the main activity java file is this..

https://github.com/vishal-android-freak/Fusion_Control/blob/master/app/src/main/java/vishal/vaf/fusioncontrol/MainActivity.java

**Comment by falcon97** [comment]
Here are the values which were getting changes when gestures get enabled as u asked :

TW_SUPPORT_NONE_SLIDE_WAKEUP = 0x00000000,
TW_SUPPORT_UP_SLIDE_WAKEUP = 0x00000001,
TW_SUPPORT_DOWN_SLIDE_WAKEUP = 0x00000002,
TW_SUPPORT_LEFT_SLIDE_WAKEUP = 0x00000004,
TW_SUPPORT_RIGHT_SLIDE_WAKEUP = 0x00000008,
TW_SUPPORT_E_SLIDE_WAKEUP = 0x00000010,
TW_SUPPORT_O_SLIDE_WAKEUP = 0x00000020,
TW_SUPPORT_W_SLIDE_WAKEUP = 0x00000040,
TW_SUPPORT_C_SLIDE_WAKEUP = 0x00000080,
TW_SUPPORT_M_SLIDE_WAKEUP = 0x00000100,
TW_SUPPORT_DOUBLE_CLICK_WAKEUP = 0x00000200,

And can u make toggle switch for each gesture instead of list view so that multiple gestures can be toggled on at the sametym..

**Comment by Grarak** [comment]
Are you sure you give me the correct file?
/sys/class/touchscreen/touchscreen_dev/gesture_wakeup
or
/sys/devices/virtual/touchscreen/touchscreen_dev/gesture_ctrl

**Comment by falcon97** [comment]
The second link is the correct link 

/sys/devices/virtual/touchscreen/touchscreen_dev/gesture_ctrl 

The changes occur here only...

**Comment by falcon97** [comment]
For multiple gestures it is addition of those values...for eg : 

If slide left , slide right , draw e is enabled...it is actually

0x00000004 + 0x00000008 + 0x00000010 = 0x0000021c..

Hope this helped u...fingers crosses..

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/30080368d96c519c14450a8775c7528db926d7ce

**Comment by falcon97** [comment]
Boom...it works...U are awesome...But there is a small bug... The slide up feature gets enabled and it is also setting on boot...but the toggle for slide up gesture remains in the off position though the gesture is turned on...gesture works fyn..but there is something wrong with the toggle...this only happens for slide up gesture...all the other toggle and gesture works gr8....

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/ed1ccc89f0654ce173a5a755af849ed9d10ddb10

**Comment by pinnamanivenkat** [comment]
Hey!
it isn't working for me on the Nougat. 

`06-15 11:56:07.890  2294  3813 I Control : saved /sys/devices/virtual/touchscreen/touchscreen_dev/gesture_ctrldouble_click
06-15 11:56:07.891  2294  3813 I Control : echo 'double_click=true' > /sys/devices/virtual/touchscreen/touchscreen_dev/gesture_ctrl`

it shows this in the logcat but the values aren't getting written to gesture_ctrl.
i did set 0770 permission to that file though the device attribute but the values aren't getting written to this file, neither can i open this file. 

Any help regarding this?
Thank you
