### ISSUE TITLE
Make "set on boot" disappear in battery section if there are no custom features 

### ISSUE THREAD

**Issue by arnavgosain** [Grarak/KernelAdiutor#76]
In case of kernels which don't have features like force fastcharging which comes under battery section there should be no set on boot switch.

**Comment by AndroidNoob69** [comment]
I was 13 years old
I loved Arnav so much
Had all his ROMs
I prayed to him every night thanking for the ROMs he gave me
My dad hears me an calls me a fagit
I know he's jealous of my devotion to Arnav
I call him a cunt
He slaps me and sends me to sleep
I'm in the bed and I'm crying
Suddenly a warmth moves towards me
It's Arnav!
He whispers in my ear: This is my ROM
I'm ready
I want to please Arnav
I boot into recovery
Take the zip and flash it
I reboot the phone and it gets stuck on a black screen
My father enters the room
Arnav looks him straight in the eyes and says: "It's all bricked now!"
He flies out of the window
Arnav is love, Arnav is life

**Comment by rudij7** [comment]
I was 13 years old
I loved Arnav so much
Had all his ROMs
I prayed to him every night thanking for the ROMs he gave me
My dad hears me an calls me a fagit
I know he's jealous of my devotion to Arnav
I call him a cunt
He slaps me and sends me to sleep
I'm in the bed and I'm crying
Suddenly a warmth moves towards me
It's Arnav!
He whispers in my ear: This is my ROM
I'm ready
I want to please Arnav
I boot into recovery
Take the zip and flash it
I reboot the phone and it gets stuck on a black screen
My father enters the room
Arnav looks him straight in the eyes and says: "It's all bricked now!"
He flies out of the window
Arnav is love, Arnav is life

**Comment by arnavgosain** [comment]
![rollin_they_see_me_hatin_they_be-177184](https://cloud.githubusercontent.com/assets/4747449/6894557/861080c8-d6f4-11e4-9656-c34180e0c3be.jpg)

**Comment by KNIGHT97** [comment]
I was 18 years old
I saw a random noob
Who just forked repos to his git and kept them there 
I laughed at him every time I saw his profile
He sees this and thinks others are fagit
While he himself is a cunt
He writes random comments here 
Suddenly a warmth comes toward me
Its that random noob
He whispers in my ear : let's fork a repository 
I'm ready
I want to please random noob
I open my github and fork it
I leave it lying there 
He says, congrats I declare you of my class
He flies out of window 
Random noob is idiot, random noob is fag

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/ae7418300bdb3b9273f35f540362a68586667f7d

**Comment by falcon97** [comment]
Also make sure "battery" check button is not available for creating a new profile if there are no custom battery features..

![screenshot_2015-04-12-18-50-50](https://cloud.githubusercontent.com/assets/10761957/7105740/6bfdae9e-e145-11e4-9f1a-e3339b4cb35d.png)
