### ISSUE TITLE
Fix input boost value being displayed wronglly

### ISSUE THREAD

**Issue by falcon97** [Grarak/KernelAdiutor#79]
When i change the input boost value...the value gets changed and the value sticks...But the app after going to another tab and returning to cpu tab or after returnin to the app after quiting shows input boost as disabled..

While fixing the value :
![screenshot_2015-04-04-08-52-55](https://cloud.githubusercontent.com/assets/10761957/6991295/fa395e22-daa8-11e4-9c8d-b02969902e74.png)

Change of value : 
![screenshot_2015-04-04-08-53-07](https://cloud.githubusercontent.com/assets/10761957/6991296/12008454-daa9-11e4-8304-eadd7fae7f45.png)

Status of value changes after returning to cpu section : 
![screenshot_2015-04-04-08-53-19](https://cloud.githubusercontent.com/assets/10761957/6991298/30ea33f6-daa9-11e4-8ab9-60bf2243da0f.png)

But the value in my phone sticks to the same value which i changed earlier..

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/48e0b1191947132bf2b5bebcedeff9276d26729a

**Comment by Grarak** [comment]
Don't know if this commits fixes that problem. Test the next beta please

**Comment by falcon97** [comment]
Yup..its fixed.. :) .. Such a quick response ur simply awesome..
