### ISSUE TITLE
Faux voltage control

### ISSUE THREAD

**Issue by banci** [Grarak/KernelAdiutor#8]
Force close on selection :(
01-08 10:59:20.119 E/AndroidRuntime(3889): FATAL EXCEPTION: AsyncTask #3
01-08 10:59:20.119 E/AndroidRuntime(3889): Process: com.grarak.kerneladiutor, PID: 3889
01-08 10:59:20.119 E/AndroidRuntime(3889): java.lang.RuntimeException: An error occured while executing doInBackground()
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.lang.Thread.run(Thread.java:818)
01-08 10:59:20.119 E/AndroidRuntime(3889): Caused by: java.lang.NullPointerException: storage == null
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.Arrays.asList(Arrays.java:155)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at com.grarak.kerneladiutor.utils.kernel.CPUVoltage.getFreqs(CPUVoltage.java:83)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at com.grarak.kerneladiutor.fragments.kernel.CPUVoltageFragment.init(CPUVoltageFragment.java:47)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at com.grarak.kerneladiutor.elements.RecyclerViewFragment$Task.doInBackground(RecyclerViewFragment.java:187)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at com.grarak.kerneladiutor.elements.RecyclerViewFragment$Task.doInBackground(RecyclerViewFragment.java:174)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-08 10:59:20.119 E/AndroidRuntime(3889): 	... 4 more
01-08 10:59:20.125 W/ActivityManager(756):   Force finishing activity com.grarak.kerneladiutor/.MainActivity
01-08 10:59:22.481 I/ActivityManager(756): START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.activities.AppCrashProxy (has extras)} from uid 1000 on display 0
01-08 10:59:22.520 I/libprocessgroup(756): Killing pid 3910 in uid 10007 as part of process group 3889
01-08 10:59:22.520 I/libprocessgroup(756): Killing pid 3942 in uid 10007 as part of process group 3889
01-08 10:59:22.521 I/libprocessgroup(756): Killing pid 3910 in uid 10007 as part of process group 3889
01-08 10:59:22.521 I/libprocessgroup(756): Killing pid 3942 in uid 10007 as part of process group 3889
01-08 10:59:22.521 I/libprocessgroup(756): Killing pid 3910 in uid 10007 as part of process group 3889
01-08 10:59:22.521 I/libprocessgroup(756): Killing pid 3942 in uid 10007 as part of process group 3889
01-08 10:59:22.522 I/libprocessgroup(756): Killing pid 3910 in uid 10007 as part of process group 3889
01-08 10:59:22.522 I/libprocessgroup(756): Killing pid 3942 in uid 10007 as part of process group 3889
01-08 10:59:22.561 I/ActivityManager(756): Process com.grarak.kerneladiutor (pid 3889) has died

full logcat: https://www.dropbox.com/s/o172wknpua8r5cq/logcat_and_device_info.zip?dl=0

**Comment by Grarak** [comment]
Could you send me the content of "/sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels"?

**Comment by Grarak** [comment]
Should be fixed with this commit
https://github.com/Grarak/KernelAdiutor/commit/c324f1119dbf5ed8e1ca5d20b8cb8cc38a9d9ebc
