### ISSUE TITLE
Support for Thunderplug CPU Hotplug

### ISSUE THREAD

**Issue by Cardinal97** [Grarak/KernelAdiutor#81]
It is a budding hotplug for octa core devices...so the values to be changed are..

Endurance mode :
/sys/kernel/thunderplug/endurance_level

support text : Endurance mode is a special powersaving mode with two levels.
Level 1 puts the device into True Quad Core mode.
Level 2 puts the device into True Dual Core mode which is more aggressive.

Values available : 
0 which is off and 1 and 2 respectively for the above modes...

Suspend CPU : 
/sys/kernel/thunderplug/suspend_cpus

Supportive text : 
Select no. of CPUs to keep online when screen is off

Values available : 
1 2 3 4 5 6 7 8

And atlast version :
/sys/kernel/thunderplug/version

**Comment by Cardinal97** [comment]
As the hotplug got an update there are some xtra features leading to xtra paths..

Toggle Hotplug On/Off : 

/sys/kernel/thunderplug/hotplug_enabled

0 to turn off and 1 to turn on

Toggle touch boost On/Off : 

/sys/kernel/thunderplug/touch_boost

0 to turn off and 1 to turn on

Load threshold :

Values are 0 to 100

Supportive text : Enabling this will start load based hot-plugging

Slider will be perfect ranging from 0 to 100

Sampling rate : 

/sys/kernel/thunderplug/sampling_rate

Values : 0 to 2500 with 50 as a step..for eg 0,50,100 etc..

Again slider will be gud...

**Comment by Grarak** [comment]
Load threshold path is missing

**Comment by Grarak** [comment]
Never mind got it

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/4490f7ed6cdd0b9f523bfd0e98e627f1121ef367

**Comment by Cardinal97** [comment]
Oh jesus...Seriously it was a bad timing from me....My intermediate exams got over yesterday and i jus started to add some of my needed features my self and first of them was this thunderplug...But you were fast enough...LOL :P 

https://github.com/Cardinal97/KernelAdiutor/commit/e5dc880848443c9e477bee675e20595956d91726
