### ISSUE TITLE
Power Efficient Workqueue Toggle

### ISSUE THREAD

**Issue by DespairFactor** [Grarak/KernelAdiutor#85]
Workqueues can be performance or power-oriented. Currently, most workqueues are
bound to the CPU they were created on. This gives good performance (due to cache
effects) at the cost of potentially waking up otherwise idle cores (Idle from
scheduler's perspective. Which may or may not be physically idle) just to
process some work. To save power, we can allow the work to be rescheduled on a
core that is already awake.

Workqueues created with the WQ_UNBOUND flag will allow some power savings.
However, we don't change the default behaviour of the system.  To enable
power-saving behaviour, a new config option CONFIG_WQ_POWER_EFFICIENT needs to
be turned on. This option can also be overridden by the
workqueue.power_efficient boot parameter.

/sys/module/workqueue/parameters/power_efficient

default is Y(this is on)
N is to turn off

**Comment by Grarak** [comment]
I need a shorter description

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/8d4571c2853e4c7bdb30bf36fc372c5582e7b223
