### ISSUE TITLE
Thermal throttling option

### ISSUE THREAD

**Issue by Vash1989** [Grarak/KernelAdiutor#9]
Add the CPU thermal threshold value option.

**Comment by Grarak** [comment]
Paths please
Am 11.01.2015 17:52 schrieb "Vash1989" <notifications@github.com>:

**Comment by Vash1989** [comment]
Maybe 
system\bin\thermal-engine-hh

**Comment by Grarak** [comment]
No that's not the path

**Comment by Vash1989** [comment]
I do not know, Sorry.

**Comment by marf28101995** [comment]
Here's the path
/sys/module/msm_thermal/parameters/temp_threshold

**Comment by Grarak** [comment]
@marf28101995 Do you have the min and max values for this one?

**Comment by marf28101995** [comment]
the default value in nexus 5 is 70 
as max you can use 95 or 99 more than that the device will melt

**Comment by Grarak** [comment]
Added!
