### ISSUE TITLE
Disable wakelock

### ISSUE THREAD

**Issue by ShahrizadAF** [Grarak/KernelAdiutor#90]
Add option to disable wlan_rx_wake, wlan_ctrl_wake and wlan_wake wakelock. Very useful for Franco kernel.

**Comment by Grarak** [comment]
I need their paths, name, values and descriptions

**Comment by ShahrizadAF** [comment]
Path : /sys/module/wakeup/parameters/

Description : Options to disable sensor_ind and other wlan wakelocks (wlan_rx_wake, wlan_ctrl_wake and wlan_wake wakelock)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/f6e6693d1b4c35f6643d68006c57cfa6f667382a
