### ISSUE TITLE
man pages or help blurbs 

### ISSUE THREAD

**Issue by jettero** [Grarak/KernelAdiutor#91]
The various kernel params have reasonably good documentation if you know where to look.  I'd be willing to write some help or cut and paste it in if there were interfaces to which it could be added. xml resources maybe? if(r=help() ) show_thingy(r);

personally, I find it very cumbersome to tweak while switching back and forth from google...

**Comment by Grarak** [comment]
I have no idea what you are trying to say

**Comment by jettero** [comment]
I'm saying those long lists of unexplained kernel tweaks and params need help docs of some kind. over commit ratio? swapiness? vfs cache pressure? 

I have some idea what they do, but I can't reasonably tweak them in an informed way without a web browser.  And switching windows in Android kinda sucks, at least compared to having two terminals side by side with man proc and bash going... 

... I was then offering to help fill in the little help blurbs (going off the kernel docs) if you gave some indication about where they'd go.  I was imagining xml resources or something, but I don't know where you'd want them.

**Comment by Grarak** [comment]
Most of the controls already have further descriptions. If you want more then send a pull request.

**Comment by jettero** [comment]
Oh, I'll just look for that then.  I don't recall seeing any further descriptions on any of the kernel params, my mistake.

**Comment by jettero** [comment]
huh, just got tired of looking at this one I guess.

**Comment by DespairFactor** [comment]
Dude, he gave you a solution, there is no reason for him to keep this open...

**Comment by Cardinal97** [comment]
If u hav descriptions for the ratios either post them in the comment...Or jus u can add them to strings and make a pull request....How can he add those descriptions w/o knowin the what u have in ur mind??

If u want the job to be simplifies jus post the descriptions with headings...U will surely get ur expected results....

**Comment by jettero** [comment]
I do plan to do this.  It just seemed odd to me to close it before I even generated the applicable pull request.

**Comment by Cardinal97** [comment]
He would open if u make a pull request now....And he actually have gave enough tym to make a pull request... didnt he?? 3 months...

Still if u wish u can make a pull request..its all about ur issue and his app...
