### ISSUE TITLE
CPU temperature

### ISSUE THREAD

**Issue by kentallenduke** [Grarak/KernelAdiutor#92]
Have kernel auditor display CPU temperature under CPU tab.

I don't know if path is necessary for this request.

**Comment by Grarak** [comment]
I need all paths of CPU temperature.
Each device has different ones.

**Comment by kentallenduke** [comment]
/sys/class/thermal_zone0/temp
That path is for Linux based systems. The path and file is found on my Android device.

**Comment by engstk** [comment]
That path is for battery temp I think

**Comment by Grarak** [comment]
/sys/class/thermal/thermal_zone0/temp
is the cpu temp
I checked on several devices
zone7 returns a different temp neither battery or cpu
and one some non qcom devices zone7 does not exist

**Comment by engstk** [comment]
You mean zone1 probably


In most devices zone0 is the same but not always.

In shqmu for instance zone0 is battery.

From what i tested zon1 is always cpu

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/d583211b2a4225edafeb683eb7e2feb7f6b092cf

**Comment by engstk** [comment]
Thanks mate
