### ISSUE TITLE
Option for mako hotplug

### ISSUE THREAD

**Issue by DerRomtester** [Grarak/KernelAdiutor#93]
Could you add min cores online for mako hotplug (not available on every kernel, the kernel needs this patch https://github.com/DerRomtester/one_plus_one/commit/02158c3c00b970af6cc2db6f47e2d05fd75c0714). So this feature isnt supported by every device that has mako hotplug inside. 
path:
/sys/devices/virtual/misc/mako_hotplug_control/min_cores_online

range from 1-4 of course

**Comment by Grarak** [comment]
part of this commit
https://github.com/Grarak/KernelAdiutor/commit/df861c9adcf84e0ee407322a8c9d70eb0574cdba
