### ISSUE TITLE
Custom terminal commands launched at boot

### ISSUE THREAD

**Issue by ParanoidNote** [Grarak/KernelAdiutor#94]
could you add a tab where the user can add their own commands that can be launched at boot?

**Comment by skulldreamz** [comment]
Wow this is a incredible request!! This would be the first ever kernel app I believe that had a shell open up strait from the app to be able to tweak from the command line. Not that you can't do it now but just having the feature to open a emulator from inside the app would put this app over the top of any out %100 it is already my favorite but flar2 and Franco and faux have very good apps as well so I think this would be a really chance to be able to be the first to do it..

**Comment by kentallenduke** [comment]
Check the init.d feature that's in the newest Adiutor release on Google Play.

**Comment by skulldreamz** [comment]
Yeah, IMHO besides SuperSU this is the best app ever to hit google play.

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/6ccf09bfac4498e7ea6ce02dc1316f973ef2a804

I hope that will do the same job
