### ISSUE TITLE
franco sound support

### ISSUE THREAD

**Issue by TheThrillseeker** [Grarak/KernelAdiutor#95]
could you add support for franco sound settings?
with franco sound my calls are mouch louder than faux sound

**Comment by DerRomtester** [comment]
You should add next time the path for the dev to your commit : 
/sys/devices/virtual/misc/soundcontrol/
Now inside are 3 files:
mic_boost           range from -20 to +20
speaker_boost    range from - 20 to +20
volume_boost     range from - 20 to +20

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/8dedcddbe56117bb62698b86f2fe2f65b07b050b
