### ISSUE TITLE
Set hostname

### ISSUE THREAD

**Issue by engstk** [Grarak/KernelAdiutor#96]
a simple interface could be added to manage hostname (goodbye wifi android endless strings)

getprop net.hostname (reads)
setprop net.hostname "new_hostname" (writes)

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/c1e5d0c3b90b9038b503bf64dd434c83fc77d372

**Comment by engstk** [comment]
Thanks mate
