### ISSUE TITLE
Request to add toggle for Exponential brightness

### ISSUE THREAD

**Issue by dexmc** [Grarak/KernelAdiutor#97]
+Willi Ye​ 

Hi, could you possibly add an option to enable this feature?

https://github.com/stratosk/kernel_msm/commit/44b3f96f553a40922635b46ed4a7fcc0361e551e

https://github.com/stratosk/kernel_msm/commit/442e153cc901e297ea517db5b5af1de5d2987e59

https://github.com/stratosk/kernel_msm/commit/77ee014218c8cb9dce5e76fc80844a32f76ea918﻿

We use this command to enable:
echo 1 > /sys/devices/i2c-0/0-0038/lm3530_br_mode﻿

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/6a3e01157ce5567dcfe8333412fe54fa756daa39
